import { BadRequestException, Injectable, NotFoundException, OnModuleDestroy, OnModuleInit } from "@nestjs/common";
import { createHmac, timingSafeEqual } from "node:crypto";
import { prisma, withTenant } from "@varejo/database";

const provider=()=>String(process.env.EMAIL_PROVIDER??"").toLowerCase();
const apiKey=()=>process.env.EMAIL_API_KEY??"";
const baseUrl=()=>process.env.PUBLIC_APP_URL??"https://vendamais-app.com";
const cleanEmail=(value:string)=>value.trim().toLowerCase();
const cleanHtml=(value:string)=>value.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"").replace(/\son\w+\s*=\s*(["']).*?\1/gi,"").replace(/javascript\s*:/gi,"");
const plain=(html:string)=>html.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();
const validEmail=(value:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);

@Injectable()
export class EmailMarketingService implements OnModuleInit,OnModuleDestroy {
  private timer?:NodeJS.Timeout; private running=false;
  onModuleInit(){this.timer=setInterval(()=>void this.work(),10_000);void this.work();}
  onModuleDestroy(){if(this.timer)clearInterval(this.timer);}
  private async audit(tenantId:string,action:string,resource:string,resourceId?:string){return prisma.auditLog.create({data:{tenantId,action,resource,resourceId,requestId:"email-marketing"}}).catch(()=>undefined);}

  async dashboard(tenantId:string){return withTenant(tenantId,async tx=>{const [contacts,campaigns,recipients]=await Promise.all([tx.emailContact.count({where:{tenantId}}),tx.emailCampaign.findMany({where:{tenantId},orderBy:{createdAt:"desc"},take:20}),tx.emailCampaignRecipient.findMany({where:{tenantId},select:{status:true}})]);const count=(...statuses:string[])=>recipients.filter(r=>statuses.includes(r.status)).length,total=recipients.length,sent=count("SENT","DELIVERED","OPENED","CLICKED"),delivered=count("DELIVERED","OPENED","CLICKED"),opened=count("OPENED","CLICKED"),clicked=count("CLICKED"),bounced=count("BOUNCED"),failed=count("FAILED"),unsubscribed=count("UNSUBSCRIBED");return{contacts,campaigns:campaigns.map(c=>this.campaign(c)),metrics:{sent,delivered,opened,clicked,bounced,failed,unsubscribed,deliveryRate:sent?delivered/sent:0,openRate:delivered?opened/delivered:0,clickRate:delivered?clicked/delivered:0,bounceRate:total?bounced/total:0},states:{sent:campaigns.filter(c=>c.status==="SENT").length,scheduled:campaigns.filter(c=>c.status==="SCHEDULED").length,processing:campaigns.filter(c=>c.status==="PROCESSING").length}};});}
  async contacts(tenantId:string,q:any){return withTenant(tenantId,async tx=>tx.emailContact.findMany({where:{tenantId,...(q.status?{status:q.status}:{}),...(q.search?{OR:[{email:{contains:q.search,mode:"insensitive"}},{firstName:{contains:q.search,mode:"insensitive"}},{company:{contains:q.search,mode:"insensitive"}}]}:{})},orderBy:{createdAt:"desc"},take:Math.min(Number(q.take)||200,500)}));}
  async createContact(tenantId:string,input:any){const email=cleanEmail(input.email);try{const result=await withTenant(tenantId,tx=>tx.emailContact.create({data:{tenantId,...this.contact(input),email}}));await this.audit(tenantId,"EMAIL_CONTACT_CREATED","email_contact",result.id);return result;}catch(e:any){if(e.code==="P2002")throw new BadRequestException("Este e-mail já existe nesta empresa.");throw e;}}
  async updateContact(tenantId:string,id:string,input:any){const current=await this.contactFor(tenantId,id);const result=await withTenant(tenantId,tx=>tx.emailContact.update({where:{id},data:{...this.contact(input),...(input.email?{email:cleanEmail(input.email)}:{})}}));await this.audit(tenantId,"EMAIL_CONTACT_UPDATED","email_contact",id);return result;}
  async deleteContact(tenantId:string,id:string){await this.contactFor(tenantId,id);await withTenant(tenantId,tx=>tx.emailContact.delete({where:{id}}));await this.audit(tenantId,"EMAIL_CONTACT_DELETED","email_contact",id);return{ok:true};}
  async applyTags(tenantId:string,ids:string[],tags:string[]){const normalized:string[]=[...new Set(tags.map((v:string)=>v.trim()).filter(Boolean))].slice(0,40);const contacts=await withTenant(tenantId,tx=>tx.emailContact.findMany({where:{tenantId,id:{in:ids}},select:{id:true,tags:true}}));await Promise.all(contacts.map(contact=>withTenant(tenantId,tx=>tx.emailContact.update({where:{id:contact.id},data:{tags:[...new Set([...contact.tags,...normalized])]}}))));return{updated:contacts.length};}
  async addMembers(tenantId:string,listId:string,ids:string[]){await this.listFor(tenantId,listId);const contacts=await withTenant(tenantId,tx=>tx.emailContact.findMany({where:{tenantId,id:{in:ids}},select:{id:true}}));await withTenant(tenantId,tx=>tx.emailListMember.createMany({data:contacts.map(c=>({emailListId:listId,emailContactId:c.id})),skipDuplicates:true}));return{added:contacts.length};}
  async csvPreview(tenantId:string,csv:string){const [header,...lines]=csv.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean),keys=this.csvLine(header).map(v=>v.trim().toLowerCase());const existing=new Set((await withTenant(tenantId,tx=>tx.emailContact.findMany({where:{tenantId},select:{email:true}}))).map(c=>c.email));let invalid=0,duplicates=0;const rows=lines.slice(0,10000).map(line=>Object.fromEntries(this.csvLine(line).map((value,index)=>[keys[index]??`coluna_${index+1}`,value.trim()])));for(const row of rows){const email=cleanEmail(row.email??row["e-mail"]??"");if(!validEmail(email))invalid++;else if(existing.has(email))duplicates++;}return{columns:keys,preview:rows.slice(0,20),total:rows.length,valid:rows.length-invalid-duplicates,invalid,duplicates};}
  async importContacts(tenantId:string,rows:any[]){let imported=0,duplicates=0,invalid=0;for(const row of rows){const email=cleanEmail(row.email??"");if(!validEmail(email)){invalid++;continue}try{await withTenant(tenantId,tx=>tx.emailContact.create({data:{tenantId,...this.contact(row),email}}));imported++;}catch(e:any){if(e.code==="P2002")duplicates++;else throw e;}}await this.audit(tenantId,"EMAIL_CONTACTS_IMPORTED","email_import");return{imported,duplicates,invalid,ignored:0,errors:0};}
  async lists(tenantId:string){return withTenant(tenantId,async tx=>(await tx.emailList.findMany({where:{tenantId},include:{_count:{select:{members:true}}},orderBy:{createdAt:"desc"}})).map(item=>({...item,contacts:item._count.members})));}
  async createList(tenantId:string,input:any){try{const value=await withTenant(tenantId,tx=>tx.emailList.create({data:{tenantId,name:input.name.trim(),description:input.description?.trim()}}));await this.audit(tenantId,"EMAIL_LIST_CREATED","email_list",value.id);return value;}catch(e:any){if(e.code==="P2002")throw new BadRequestException("Já existe uma lista com este nome.");throw e;}}
  async updateList(tenantId:string,id:string,input:any){await this.listFor(tenantId,id);return withTenant(tenantId,tx=>tx.emailList.update({where:{id},data:{name:input.name.trim(),description:input.description?.trim()}}));}
  async deleteList(tenantId:string,id:string){await this.listFor(tenantId,id);await withTenant(tenantId,tx=>tx.emailList.delete({where:{id}}));await this.audit(tenantId,"EMAIL_LIST_DELETED","email_list",id);return{ok:true};}
  async templates(tenantId:string){return withTenant(tenantId,tx=>tx.emailTemplate.findMany({where:{tenantId},orderBy:{updatedAt:"desc"}}));}
  async createTemplate(tenantId:string,input:any){return withTenant(tenantId,tx=>tx.emailTemplate.create({data:{tenantId,name:input.name.trim(),subject:input.subject?.trim(),html:cleanHtml(input.html),text:input.text?.trim()||plain(input.html)}}));}
  async updateTemplate(tenantId:string,id:string,input:any){await this.templateFor(tenantId,id);return withTenant(tenantId,tx=>tx.emailTemplate.update({where:{id},data:{name:input.name.trim(),subject:input.subject?.trim(),html:cleanHtml(input.html),text:input.text?.trim()||plain(input.html)}}));}
  async deleteTemplate(tenantId:string,id:string){await this.templateFor(tenantId,id);await withTenant(tenantId,tx=>tx.emailTemplate.delete({where:{id}}));return{ok:true};}
  async campaigns(tenantId:string){return withTenant(tenantId,async tx=>(await tx.emailCampaign.findMany({where:{tenantId},include:{list:true,_count:{select:{recipients:true}}},orderBy:{createdAt:"desc"}})).map(c=>({...this.campaign(c),recipients:c._count.recipients})));}
  async createCampaign(tenantId:string,input:any){if(input.listId)await this.listFor(tenantId,input.listId);const value=await withTenant(tenantId,tx=>tx.emailCampaign.create({data:{tenantId,...this.campaignInput(input)}}));await this.audit(tenantId,"EMAIL_CAMPAIGN_CREATED","email_campaign",value.id);return this.campaign(value);}
  async updateCampaign(tenantId:string,id:string,input:any){const current=await this.campaignFor(tenantId,id);if(current.status!=="DRAFT")throw new BadRequestException("Somente campanhas em rascunho podem ser alteradas.");if(input.listId)await this.listFor(tenantId,input.listId);return this.campaign(await withTenant(tenantId,tx=>tx.emailCampaign.update({where:{id},data:this.campaignInput(input)})));}
  async schedule(tenantId:string,id:string,scheduledAt?:string){const campaign=await this.campaignFor(tenantId,id);if(!["DRAFT","PAUSED"].includes(campaign.status))throw new BadRequestException("Esta campanha não pode ser agendada.");const when=scheduledAt?new Date(scheduledAt):new Date();if(Number.isNaN(when.getTime())||when<new Date(Date.now()-5000))throw new BadRequestException("Informe uma data de envio válida.");const recipientCount=await this.enqueue(tenantId,campaign);await withTenant(tenantId,tx=>tx.emailCampaign.update({where:{id},data:{status:"SCHEDULED",scheduledAt:when}}));await this.audit(tenantId,"EMAIL_CAMPAIGN_SCHEDULED","email_campaign",id);return{queued:recipientCount,scheduledAt:when};}
  async pause(tenantId:string,id:string){const campaign=await this.campaignFor(tenantId,id);if(!["SCHEDULED","PROCESSING"].includes(campaign.status))throw new BadRequestException("Esta campanha não está em envio.");return withTenant(tenantId,tx=>tx.emailCampaign.update({where:{id},data:{status:"PAUSED"}}));}
  async cancel(tenantId:string,id:string){const campaign=await this.campaignFor(tenantId,id);if(["SENT","CANCELED"].includes(campaign.status))throw new BadRequestException("Esta campanha não pode ser cancelada.");await Promise.all([withTenant(tenantId,tx=>tx.emailCampaign.update({where:{id},data:{status:"CANCELED"}})),withTenant(tenantId,tx=>tx.emailCampaignRecipient.updateMany({where:{campaignId:id,status:"QUEUED"},data:{status:"FAILED",errorMessage:"Campanha cancelada."}}))]);await this.audit(tenantId,"EMAIL_CAMPAIGN_CANCELED","email_campaign",id);return{ok:true};}
  async sendTest(tenantId:string,id:string,email:string){const campaign=await this.campaignFor(tenantId,id);await this.send({to:cleanEmail(email),from:`${campaign.fromName} <${campaign.fromEmail}>`,replyTo:campaign.replyTo??undefined,subject:`[TESTE] ${campaign.subject}`,html:this.render(campaign.html,{email,firstName:"Contato de teste"},tenantId,"test"),text:campaign.text??plain(campaign.html)});return{ok:true};}
  async logs(tenantId:string,q:any){return withTenant(tenantId,tx=>tx.emailCampaignRecipient.findMany({where:{tenantId,...(q.status?{status:q.status}:{}),...(q.email?{email:{contains:q.email,mode:"insensitive"}}:{})},include:{campaign:{select:{name:true,subject:true}},contact:{select:{firstName:true,lastName:true}}},orderBy:{updatedAt:"desc"},take:Math.min(Number(q.take)||200,500)}));}
  async settings(tenantId:string){const saved=await withTenant(tenantId,tx=>tx.emailMarketingSettings.findUnique({where:{tenantId}}));return{...saved,provider:provider()||"not_configured",configured:!!(provider()==="resend"&&apiKey())};}
  async saveSettings(tenantId:string,input:any){const value=await withTenant(tenantId,tx=>tx.emailMarketingSettings.upsert({where:{tenantId},create:{tenantId,...input},update:input}));await this.audit(tenantId,"EMAIL_SETTINGS_UPDATED","email_settings",tenantId);return value;}
  async verifyConfiguration(){if(provider()!=="resend"||!apiKey())return{ok:false,status:"NOT_CONFIGURED",message:"Configure EMAIL_PROVIDER=resend e EMAIL_API_KEY no servidor."};return{ok:true,status:"CONFIGURED"};}
  async unsubscribe(token:string){const [id,signature]=token.split(".");if(!id||!signature||!this.validToken(id,signature))throw new BadRequestException("Link de descadastro inválido.");const contact=await prisma.emailContact.findUnique({where:{id}});if(!contact)throw new NotFoundException("Contato não encontrado.");await prisma.$transaction([prisma.emailContact.update({where:{id},data:{status:"UNSUBSCRIBED"}}),prisma.emailCampaignRecipient.updateMany({where:{contactId:id,status:{in:["QUEUED","SENDING"]}},data:{status:"UNSUBSCRIBED",unsubscribedAt:new Date()}})]);return{ok:true,email:contact.email};}
  async processWebhook(input:any,secret?:string){if(process.env.EMAIL_WEBHOOK_SECRET&&secret!==process.env.EMAIL_WEBHOOK_SECRET)throw new BadRequestException("Assinatura de webhook inválida.");const data=input.data??input,event=String(input.type??data.type??"").toLowerCase(),messageId=String(data.email_id??data.message_id??data.messageId??"");if(!messageId)return{ok:true};const recipient=await prisma.emailCampaignRecipient.findFirst({where:{providerMessageId:messageId}});if(!recipient)return{ok:true};const eventId=String(input.id??data.id??"")||undefined;try{await prisma.emailProviderEvent.create({data:{tenantId:recipient.tenantId,providerEventId:eventId,providerMessageId:messageId,eventType:event,payload:data}})}catch(e:any){if(e.code==="P2002")return{ok:true};throw e}const mapped=event.includes("bounce")?"BOUNCED":event.includes("click")?"CLICKED":event.includes("open")?"OPENED":event.includes("deliver")?"DELIVERED":event.includes("fail")?"FAILED":undefined;if(!mapped)return{ok:true};const now=new Date(),field=mapped==="BOUNCED"?{bouncedAt:now}:mapped==="CLICKED"?{clickedAt:now}:mapped==="OPENED"?{openedAt:now}:mapped==="DELIVERED"?{deliveredAt:now}:{failedAt:now};await prisma.$transaction([prisma.emailCampaignRecipient.update({where:{id:recipient.id},data:{status:mapped as any,...field}}),...(mapped==="BOUNCED"?[prisma.emailContact.update({where:{id:recipient.contactId},data:{status:"BOUNCED"}})]:[])]);return{ok:true};}
  private async work(){if(this.running||provider()!=="resend"||!apiKey())return;this.running=true;try{const now=new Date(),campaigns=await prisma.emailCampaign.findMany({where:{status:{in:["SCHEDULED","PROCESSING"]},scheduledAt:{lte:now}},take:20});for(const campaign of campaigns){await prisma.emailCampaign.update({where:{id:campaign.id},data:{status:"PROCESSING",startedAt:campaign.startedAt??now}});const settings=await prisma.emailMarketingSettings.findUnique({where:{tenantId:campaign.tenantId}}),perMinute=Math.max(1,Math.min(settings?.ratePerMinute??Number(process.env.EMAIL_SEND_RATE_PER_MINUTE??60),10_000)),batch=Math.max(1,Math.ceil(perMinute/6));const jobs=await prisma.emailCampaignRecipient.findMany({where:{campaignId:campaign.id,status:"QUEUED",availableAt:{lte:now}},take:batch,include:{contact:true}});for(const job of jobs){if(job.contact.status!=="ACTIVE"){await prisma.emailCampaignRecipient.update({where:{id:job.id},data:{status:"UNSUBSCRIBED",unsubscribedAt:new Date()}});continue}await prisma.emailCampaignRecipient.update({where:{id:job.id},data:{status:"SENDING",attempts:{increment:1}}});try{const response=await this.send({to:job.email,from:`${campaign.fromName} <${campaign.fromEmail}>`,replyTo:campaign.replyTo??undefined,subject:this.render(campaign.subject,job.contact,campaign.tenantId,job.contactId),html:this.render(campaign.html,job.contact,campaign.tenantId,job.contactId),text:this.render(campaign.text??plain(campaign.html),job.contact,campaign.tenantId,job.contactId)});await prisma.emailCampaignRecipient.update({where:{id:job.id},data:{status:"SENT",providerMessageId:response.id,sentAt:new Date()}})}catch(error:any){const attempts=job.attempts+1,retry=attempts<3;await prisma.emailCampaignRecipient.update({where:{id:job.id},data:retry?{status:"QUEUED",availableAt:new Date(Date.now()+Math.pow(2,attempts)*60_000),errorMessage:String(error.message??error).slice(0,2000)}:{status:"FAILED",failedAt:new Date(),errorMessage:String(error.message??error).slice(0,2000)}})}}const pending=await prisma.emailCampaignRecipient.count({where:{campaignId:campaign.id,status:{in:["QUEUED","SENDING"]}}});if(!pending)await prisma.emailCampaign.update({where:{id:campaign.id},data:{status:"SENT",completedAt:new Date()}})}}finally{this.running=false}}
  private async enqueue(tenantId:string,campaign:any){const contacts=await withTenant(tenantId,tx=>tx.emailContact.findMany({where:{tenantId,status:"ACTIVE",...(campaign.listId?{lists:{some:{emailListId:campaign.listId}}}:{}),...(campaign.segment?.tags?.length?{tags:{hasSome:campaign.segment.tags}}:{})},select:{id:true,email:true}}));await withTenant(tenantId,tx=>tx.emailCampaignRecipient.createMany({data:contacts.map(c=>({tenantId,campaignId:campaign.id,contactId:c.id,email:c.email})),skipDuplicates:true}));return contacts.length;}
  private async send(input:{to:string;from:string;replyTo?:string;subject:string;html:string;text:string}){if(provider()!=="resend"||!apiKey())throw new Error("Provedor de e-mail não configurado.");const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${apiKey()}`,"Content-Type":"application/json","Idempotency-Key":createHmac("sha256",process.env.EMAIL_WEBHOOK_SECRET??"email").update(`${input.to}:${input.subject}:${input.html}`).digest("hex")},body:JSON.stringify({from:input.from,to:[input.to],reply_to:input.replyTo,subject:input.subject,html:input.html,text:input.text})});const data:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message??"Falha no provedor de e-mail.");return{id:String(data.id??"")};}
  private contact(input:any){const tags=[...new Set<string>((Array.isArray(input.tags)?input.tags:[]).map((v:unknown)=>String(v).trim()).filter(Boolean) as string[])];return{firstName:input.firstName?.trim()||null,lastName:input.lastName?.trim()||null,phone:input.phone?.trim()||null,company:input.company?.trim()||null,tags,source:input.source?.trim()||null,notes:input.notes?.trim()||null,...(input.status?{status:input.status}:{})};}
  private campaignInput(input:any){return{...input,name:input.name.trim(),subject:input.subject.trim(),fromName:input.fromName.trim(),fromEmail:cleanEmail(input.fromEmail),replyTo:input.replyTo?cleanEmail(input.replyTo):null,html:cleanHtml(input.html),text:input.text?.trim()||plain(input.html),segment:input.segment??null};}
  private campaign(value:any){return{...value,html:undefined,text:undefined};}
  private render(value:string,contact:any,tenantId:string,contactId:string){const token=`${contactId}.${createHmac("sha256",process.env.EMAIL_UNSUBSCRIBE_SECRET??process.env.EMAIL_WEBHOOK_SECRET??"change-this-secret").update(contactId).digest("hex")}`;return(value??"").replace(/{{nome}}/g,contact.firstName??"").replace(/{{sobrenome}}/g,contact.lastName??"").replace(/{{email}}/g,contact.email??"").replace(/{{empresa}}/g,contact.company??"").replace(/{{unsubscribe_url}}/g,`${baseUrl()}/api/email-marketing/unsubscribe?token=${encodeURIComponent(token)}`);}
  private validToken(id:string,signature:string){const expected=createHmac("sha256",process.env.EMAIL_UNSUBSCRIBE_SECRET??process.env.EMAIL_WEBHOOK_SECRET??"change-this-secret").update(id).digest("hex");return signature.length===expected.length&&timingSafeEqual(Buffer.from(signature),Buffer.from(expected));}
  private csvLine(line:string){const values:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if((c===","||c===";")&&!quoted){values.push(value);value=""}else value+=c}values.push(value);return values;}
  private async contactFor(tenantId:string,id:string){const result=await withTenant(tenantId,tx=>tx.emailContact.findFirst({where:{id,tenantId}}));if(!result)throw new NotFoundException("Contato não encontrado.");return result;}
  private async listFor(tenantId:string,id:string){const result=await withTenant(tenantId,tx=>tx.emailList.findFirst({where:{id,tenantId}}));if(!result)throw new NotFoundException("Lista não encontrada.");return result;}
  private async templateFor(tenantId:string,id:string){const result=await withTenant(tenantId,tx=>tx.emailTemplate.findFirst({where:{id,tenantId}}));if(!result)throw new NotFoundException("Template não encontrado.");return result;}
  private async campaignFor(tenantId:string,id:string){const result=await withTenant(tenantId,tx=>tx.emailCampaign.findFirst({where:{id,tenantId}}));if(!result)throw new NotFoundException("Campanha não encontrada.");return result;}
}
