export type DigitalFormat = "PDF" | "KINDLE";
export type DigitalCategory = "NEGOCIOS" | "TECNOLOGIA" | "ESPIRITUALIDADE" | "SAUDE";
export type DigitalCurrency = "BRL" | "USD";
export type DigitalProduct = { slug:string; category:DigitalCategory; title:string; hook:string; pages:number; pdfFile:string; kindleFile:string; prices?:Partial<Record<DigitalFormat,number>>; currency?:DigitalCurrency; language?:"pt-BR"|"en"; translationOf?:string };

const STANDARD_PRICES:Record<DigitalFormat,number>={PDF:11.99,KINDLE:39.99};
export const digitalPrices=(product:DigitalProduct):Record<DigitalFormat,number>=>({...STANDARD_PRICES,...product.prices});
export const digitalCurrency=(product:DigitalProduct):DigitalCurrency=>product.currency??"BRL";

export const DIGITAL_PRODUCTS:DigitalProduct[]=[
  {slug:"as-armas-da-persuasao",category:"NEGOCIOS",title:"As Armas da Persuasão",hook:"Princípios psicológicos para reconhecer como decisões, negociações e escolhas são influenciadas no dia a dia.",pages:225,prices:{PDF:7.90,KINDLE:19.90},pdfFile:"as-armas-da-persuasao.pdf",kindleFile:"as-armas-da-persuasao.epub"},
  {slug:"codigos-de-energia-volume-1",category:"ESPIRITUALIDADE",title:"Vibracional — Códigos de Energia, Volume 1",hook:"Símbolos, frequências e relações energéticas apresentados em uma jornada visual.",pages:17,prices:{PDF:7.90,KINDLE:19.90},pdfFile:"codigos-de-energia-volume-1.pdf",kindleFile:"codigos-de-energia-volume-1.epub"},
  {slug:"vibrational-energy-codes-volume-1-en",category:"ESPIRITUALIDADE",title:"Vibrational Energy Codes — Volume 1",hook:"A visual journey through symbols, intention and reflective energy practices.",pages:17,prices:{PDF:5,KINDLE:9.90},currency:"USD",language:"en",translationOf:"codigos-de-energia-volume-1",pdfFile:"vibrational-energy-codes-volume-1-en.pdf",kindleFile:"vibrational-energy-codes-volume-1-en.epub"},
  {slug:"livro-da-sabedoria-volume-1",category:"ESPIRITUALIDADE",title:"Livro da Sabedoria — Volume 1",hook:"Uma leitura sobre conhecimento, bem e mal e os símbolos que atravessam essa dualidade.",pages:122,prices:{PDF:11.90,KINDLE:19.90},pdfFile:"livro-da-sabedoria-volume-1.pdf",kindleFile:"livro-da-sabedoria-volume-1.epub"},
  {slug:"os-manuscritos-escondidos-volume-2",category:"ESPIRITUALIDADE",title:"Os Manuscritos Escondidos — Volume 2",hook:"Conhecimentos, símbolos e manuscritos reunidos em uma obra extensa e ilustrada.",pages:209,prices:{PDF:11.90,KINDLE:19.90},pdfFile:"os-manuscritos-escondidos-volume-2.pdf",kindleFile:"os-manuscritos-escondidos-volume-2.epub"},
  {slug:"livro-da-sabedoria-volume-3-parte-1",category:"ESPIRITUALIDADE",title:"Livro da Sabedoria, Volume 3 — A Nova Era, Parte 1",hook:"Reflexões sobre consciência, desejo, transformação e os caminhos de uma nova era.",pages:288,prices:{PDF:7.90,KINDLE:19.90},pdfFile:"livro-da-sabedoria-volume-3-parte-1.pdf",kindleFile:"livro-da-sabedoria-volume-3-parte-1.epub"},
  {slug:"livro-da-sabedoria-volume-3-parte-2",category:"ESPIRITUALIDADE",title:"Livro da Sabedoria, Volume 3 — A Nova Era, Parte 2",hook:"A continuação da obra, aprofundando escolhas, emoções e níveis de consciência.",pages:62,prices:{PDF:7.90,KINDLE:19.90},pdfFile:"livro-da-sabedoria-volume-3-parte-2.pdf",kindleFile:"livro-da-sabedoria-volume-3-parte-2.epub"},
  {slug:"geometria-sagrada-universal",category:"ESPIRITUALIDADE",title:"A Geometria Sagrada Universal",hook:"Descubra padrões e proporções associados à natureza, ao ser humano e ao universo.",pages:34,prices:{PDF:8.90,KINDLE:19.90},pdfFile:"geometria-sagrada-universal.pdf",kindleFile:"geometria-sagrada-universal.epub"},
  {slug:"como-descalcificar-a-glandula-pineal",category:"SAUDE",title:"Como Descalcificar a Glândula Pineal",hook:"Um guia ilustrado sobre a glândula pineal e práticas apresentadas pelo autor.",pages:109,prices:{PDF:8.90,KINDLE:19.90},pdfFile:"como-descalcificar-a-glandula-pineal.pdf",kindleFile:"como-descalcificar-a-glandula-pineal.epub"},
  {slug:"astrologia-cabalista",category:"ESPIRITUALIDADE",title:"Astrologia Cabalista",hook:"Uma introdução visual às relações entre astrologia, símbolos e tradição cabalista.",pages:171,prices:{PDF:8.90,KINDLE:19.90},pdfFile:"astrologia-cabalista.pdf",kindleFile:"astrologia-cabalista.epub"},
  {slug:"tabuas-de-esmeralda-de-thoth",category:"ESPIRITUALIDADE",title:"As Tábuas de Esmeralda de Thoth",hook:"Tradução e interpretação de um dos textos mais conhecidos da tradição hermética.",pages:90,prices:{PDF:9.90,KINDLE:19.90},pdfFile:"tabuas-de-esmeralda-de-thoth.pdf",kindleFile:"tabuas-de-esmeralda-de-thoth.epub"},
  {slug:"despertar-alcalino-parte-1",category:"SAUDE",title:"Despertar Alcalino — Parte 1",hook:"A abertura de uma série sobre alimentação, hábitos e a busca por saúde verdadeira.",pages:9,prices:{PDF:6.90,KINDLE:19.90},pdfFile:"despertar-alcalino-parte-1.pdf",kindleFile:"despertar-alcalino-parte-1.epub"},
  {slug:"despertar-alcalino-parte-2",category:"SAUDE",title:"Despertar Alcalino — Parte 2",hook:"Uma leitura provocativa sobre indústria, escolhas alimentares e comportamento.",pages:16,prices:{PDF:6.90,KINDLE:19.90},pdfFile:"despertar-alcalino-parte-2.pdf",kindleFile:"despertar-alcalino-parte-2.epub"},
  {slug:"despertar-alcalino-parte-3",category:"SAUDE",title:"Despertar Alcalino — Parte 3",hook:"Compare alimentos orgânicos e industrializados e descubra os argumentos da obra.",pages:14,prices:{PDF:6.90,KINDLE:19.90},pdfFile:"despertar-alcalino-parte-3.pdf",kindleFile:"despertar-alcalino-parte-3.epub"},
  {slug:"despertar-alcalino-parte-4",category:"SAUDE",title:"Despertar Alcalino — Parte 4",hook:"Mentalidade, consciência e a ideia de que mudanças profundas começam por dentro.",pages:17,prices:{PDF:6.90,KINDLE:19.90},pdfFile:"despertar-alcalino-parte-4.pdf",kindleFile:"despertar-alcalino-parte-4.epub"},
  {slug:"pai-rico-pai-pobre-edicao-de-20-anos",category:"NEGOCIOS",title:"Pai Rico, Pai Pobre — Edição de 20 Anos",hook:"Uma leitura sobre educação financeira, ativos, passivos e escolhas para construir mais autonomia.",pages:308,prices:{PDF:7.90,KINDLE:19.90},pdfFile:"pai-rico-pai-pobre-edicao-de-20-anos.pdf",kindleFile:"pai-rico-pai-pobre-edicao-de-20-anos.epub"},
  {slug:"introducao-a-inteligencia-artificial",category:"TECNOLOGIA",title:"Introdução à Inteligência Artificial",hook:"Uma base prática para entender conceitos, aplicações e impactos da inteligência artificial.",pages:200,prices:{PDF:6.90,KINDLE:19.90},pdfFile:"introducao-a-inteligencia-artificial.pdf",kindleFile:"introducao-a-inteligencia-artificial.epub"},
  {slug:"manual-de-inteligencia-artificial",category:"TECNOLOGIA",title:"Manual de Inteligência Artificial",hook:"Um guia completo para compreender fundamentos, aplicações e caminhos da inteligência artificial.",pages:326,prices:{PDF:8.90,KINDLE:19.90},pdfFile:"manual-de-inteligencia-artificial.pdf",kindleFile:"manual-de-inteligencia-artificial.epub"},
  {slug:"filho-do-fogo-daniel-mastral-volume-1",category:"ESPIRITUALIDADE",title:"Filho do Fogo — Daniel Mastral, Volume I",hook:"O primeiro volume de uma obra sobre simbolismo, espiritualidade e experiências narradas pelos autores.",pages:330,prices:{PDF:8.90,KINDLE:19.90},pdfFile:"filho-do-fogo-daniel-mastral-volume-1.pdf",kindleFile:"filho-do-fogo-daniel-mastral-volume-1.epub"},
  {slug:"filho-do-fogo-daniel-mastral-volume-2",category:"ESPIRITUALIDADE",title:"Filho do Fogo — Daniel Mastral, Volume II",hook:"A continuação da obra, reunindo reflexões e relatos apresentados pelos autores.",pages:549,prices:{PDF:8.90,KINDLE:19.90},pdfFile:"filho-do-fogo-daniel-mastral-volume-2.pdf",kindleFile:"filho-do-fogo-daniel-mastral-volume-2.epub"},
  {slug:"ele-veio-para-libertar-os-cativos",category:"ESPIRITUALIDADE",title:"Ele Veio para Libertar os Cativos — Rebecca Brown",hook:"Um relato de fé que reúne experiências narradas pela autora e reflexões sobre espiritualidade e libertação.",pages:244,prices:{PDF:11.90,KINDLE:19.90},pdfFile:"ele-veio-para-libertar-os-cativos.pdf",kindleFile:"ele-veio-para-libertar-os-cativos.epub"}
];

export const digitalPrice=(product:DigitalProduct,format:DigitalFormat)=>digitalPrices(product)[format];
