"use client";
import { FormEvent, useEffect, useState } from "react";
import { request } from "./api-client";

type Tab="Dashboard"|"Campanhas"|"Contatos"|"Listas"|"Templates"|"Configurações"|"Logs";
const tabs:Tab[]=["Dashboard","Campanhas","Contatos","Listas","Templates","Configurações","Logs"];
export function EmailMarketing({token}:{token:string}){
 const[tab,setTab]=useState<Tab>("Dashboard"),[data,setData]=useState<any>({}),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{try{const path=tab==="Dashboard"?"/email-marketing/dashboard":tab==="Contatos"?"/email-marketing/contacts":tab==="Listas"?"/email-marketing/lists":tab==="Templates"?"/email-marketing/templates":tab==="Campanhas"?"/email-marketing/campaigns":tab==="Logs"?"/email-marketing/logs":"/email-marketing/settings";setData(await request(path,token));setError("")}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void load()},[tab]);
 async function submit(path:string,event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await request(path,token,{method:"POST",body:JSON.stringify(Object.fromEntries(form))});setMessage("Informações salvas com sucesso.");event.currentTarget.reset();await load()}catch(e){setError((e as Error).message)}}
 return <section className="email-marketing"><header><div><small>COMUNICAÇÃO COM CLIENTES</small><h2>E-mail Marketing</h2><p>Campanhas, contatos e resultados organizados por empresa.</p></div><button className="secondary" onClick={()=>void load()}>Atualizar</button></header><nav className="email-tabs">{tabs.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}
 {tab==="Dashboard"&&<Dashboard data={data}/>} {tab==="Contatos"&&<><form className="email-form" onSubmit={e=>void submit("/email-marketing/contacts",e)}><h3>Novo contato</h3><input name="firstName" placeholder="Nome"/><input name="lastName" placeholder="Sobrenome"/><input name="email" type="email" placeholder="E-mail" required/><input name="company" placeholder="Empresa (opcional)"/><input name="source" placeholder="Origem"/><button>Salvar contato</button></form><List title="Contatos" rows={Array.isArray(data)?data:[]} fields={["firstName","lastName","email","company","status"]}/></>}
 {tab==="Listas"&&<><form className="email-form" onSubmit={e=>void submit("/email-marketing/lists",e)}><h3>Nova lista</h3><input name="name" placeholder="Nome da lista" required/><input name="description" placeholder="Descrição"/><button>Criar lista</button></form><List title="Listas" rows={Array.isArray(data)?data:[]} fields={["name","description","contacts","createdAt"]}/></>}
 {tab==="Templates"&&<><form className="email-form email-editor" onSubmit={e=>void submit("/email-marketing/templates",e)}><h3>Novo template</h3><input name="name" placeholder="Nome interno" required/><input name="subject" placeholder="Assunto padrão"/><textarea name="html" placeholder="HTML do e-mail. Use {{nome}}, {{email}}, {{empresa}} e {{unsubscribe_url}}." required/><textarea name="text" placeholder="Versão texto (opcional)"/><button>Salvar template</button></form><List title="Templates" rows={Array.isArray(data)?data:[]} fields={["name","subject","updatedAt"]}/></>}
 {tab==="Campanhas"&&<><form className="email-form email-editor" onSubmit={e=>void submit("/email-marketing/campaigns",e)}><h3>Nova campanha</h3><input name="name" placeholder="Nome interno" required/><input name="subject" placeholder="Assunto" required/><input name="fromName" placeholder="Nome do remetente" required/><input name="fromEmail" type="email" placeholder="E-mail do remetente" required/><input name="replyTo" type="email" placeholder="Reply-to (opcional)"/><textarea name="html" placeholder="Conteúdo HTML — use {{nome}}, {{email}} e {{unsubscribe_url}}." required/><button>Salvar rascunho</button></form><List title="Campanhas" rows={Array.isArray(data)?data:[]} fields={["name","subject","status","recipients","scheduledAt"]}/></>}
 {tab==="Configurações"&&<Settings data={data} token={token} onSaved={async()=>{setMessage("Configurações salvas.");await load()}}/>}{tab==="Logs"&&<List title="Logs de envio" rows={Array.isArray(data)?data:[]} fields={["email","status","providerMessageId","updatedAt"]}/>}</section>
}
function Dashboard({data}:{data:any}){const m=data.metrics??{},s=data.states??{};return <><div className="email-metrics">{[["Contatos",data.contacts],["Enviados",m.sent],["Entregues",m.delivered],["Abertos",m.opened],["Cliques",m.clicked],["Bounces",m.bounced],["Falhas",m.failed],["Descadastros",m.unsubscribed]].map(([name,value])=><article key={String(name)}><small>{name}</small><strong>{value??0}</strong></article>)}</div><p className="email-empty">{!data.contacts?"Cadastre contatos e crie sua primeira campanha para acompanhar os resultados.":`${s.scheduled??0} campanha(s) agendada(s) e ${s.processing??0} em processamento.`}</p></>}
function List({title,rows,fields}:{title:string;rows:any[];fields:string[]}){return <section className="email-list"><h3>{title}</h3>{rows.length?<div className="table"><div className="email-row email-head">{fields.map(field=><span key={field}>{field}</span>)}</div>{rows.map(row=><div className="email-row" key={row.id}>{fields.map(field=><span key={field}>{row[field] instanceof Date?row[field].toLocaleString():String(row[field]??"—")}</span>)}</div>)}</div>:<p className="email-empty">Nenhum registro por enquanto.</p>}</section>}
function Settings({data,token,onSaved}:{data:any;token:string;onSaved:()=>Promise<void>}){const[message,setMessage]=useState("");return <form className="email-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await request("/email-marketing/settings",token,{method:"PUT",body:JSON.stringify(Object.fromEntries(f))});setMessage("Configurações salvas.");await onSaved()}catch(err){setMessage((err as Error).message)}}}><h3>Remetente e velocidade</h3><input name="fromName" defaultValue={data.fromName??""} placeholder="Nome do remetente"/><input name="fromEmail" type="email" defaultValue={data.fromEmail??""} placeholder="E-mail do remetente"/><input name="replyTo" type="email" defaultValue={data.replyTo??""} placeholder="Reply-to"/><input name="ratePerMinute" type="number" min="1" defaultValue={data.ratePerMinute??60} placeholder="Envios por minuto"/><button>Salvar configurações</button><p>Provedor: {data.provider??"não configurado"} · {data.configured?"configurado":"aguardando credenciais do servidor"}</p>{message&&<div className="notice">{message}</div>}</form>}
