"use client";

import { useEffect, useState } from "react";

type Locale = "pt-BR" | "en";

const english: Record<string, string> = {
  "PRIVACIDADE E TRANSPARÊNCIA": "PRIVACY AND TRANSPARENCY",
  "Dados de acesso": "Access data",
  "Ativar notificações no Mac": "Enable Mac notifications",
  "Notificações ativadas": "Notifications enabled",
  "Notificações do Mac ativadas para novos cadastros.": "Mac notifications enabled for new registrations.",
  "Você será avisado aqui no Mac quando houver um novo cadastro.": "You will be notified on this Mac when there is a new registration.",
  "Permissão de notificações não foi concedida. Ative-a nas configurações do navegador.": "Notification permission was not granted. Enable it in your browser settings.",
  "Este navegador não oferece notificações.": "This browser does not support notifications.",
  "Novo cadastro no Venda+": "New Venda+ registration",
  "Para proteger e melhorar o Venda+, registramos informações técnicas de acesso às páginas públicas: endereço IP, data e hora, página acessada, origem, tipo de dispositivo, navegador, sistema, idioma, fuso horário e localização aproximada disponibilizada pela infraestrutura.": "To protect and improve Venda+, we record technical information about access to public pages: IP address, date and time, page visited, referrer, device type, browser, operating system, language, time zone and approximate location provided by the infrastructure.",
  "Essas informações ficam disponíveis somente à administração, não são vendidas e são usadas para segurança, medição de audiência e melhoria do serviço. O histórico técnico de visitas é mantido por até 365 dias.": "This information is available only to administration, is not sold, and is used for security, audience measurement and service improvement. Technical visit history is retained for up to 365 days.",
  "As respostas voluntárias do questionário ficam armazenadas para atendimento e compreensão das necessidades informadas. Para solicitar informações, correção ou exclusão, fale pelo WhatsApp": "Voluntary questionnaire responses are stored for support and to understand the needs shared. To request information, correction or deletion, contact us by WhatsApp",
  "Voltar à tela inicial": "Back to home",
  "Capa": "Cover",
  "Página": "Page",
  "Não deixe detention se perder entre o dock e o pagamento.": "Stop letting detention get lost between the dock and payment.",
  "Para carriers, fleets e owner-operators nos Estados Unidos: registre o load e o broker, guarde os termos da rate confirmation, marque arrival e departure e acompanhe cada claim até o status pago.": "For U.S. carriers, fleets and owner-operators: record the load and broker, keep rate-confirmation terms, mark arrival and departure, and track every claim through paid status.",
  "Conhecer o módulo de Detention Recovery": "Explore the Detention Recovery module",
  "Fluxo operacional. Sem promessa de recuperação ou resultado financeiro.": "Operational workflow. No promise of recovery or financial results.",
  "Transportation Detention Recovery": "Transportation Detention Recovery",
  "Recupere detention com evidências da carga.": "Recover detention with load evidence.",
  "Cadastre o load, broker e termos da rate confirmation. Registre chegada e saída, calcule o valor e acompanhe o claim até o pagamento.": "Register the load, broker and rate-confirmation terms. Record arrival and departure, calculate the amount and track the claim through payment.",
  "Novo load": "New load",
  "Fechar cadastro": "Close form",
  "Pronto para expansão": "Ready to expand",
  "Detention ativo agora": "Detention active now",
  "Os próximos tipos já possuem base própria no módulo.": "The next types already have their own foundation in the module.",
  "Loads abertos": "Open loads",
  "Em andamento": "In progress",
  "Prontos para claim": "Ready for claim",
  "Com chegada e saída": "With arrival and departure",
  "Claims enviados": "Claims submitted",
  "Aguardando broker": "Waiting for broker",
  "Recuperado": "Recovered",
  "Claims pagos": "Paid claims",
  "Termos informados por você": "Terms entered by you",
  "O cálculo usa o tempo após a franquia e arredonda cada hora iniciada.": "The calculation uses time after free time and rounds each started hour.",
  "Load number": "Load number",
  "Broker": "Broker",
  "Broker email": "Broker email",
  "Broker phone": "Broker phone",
  "Rate confirmation #": "Rate confirmation #",
  "Load rate (USD)": "Load rate (USD)",
  "Free time (minutes)": "Free time (minutes)",
  "Detention rate / hour (USD)": "Detention rate / hour (USD)",
  "Minimum billable minutes": "Minimum billable minutes",
  "Rate confirmation terms": "Rate confirmation terms",
  "Notes": "Notes",
  "Criar load": "Create load",
  "Salvando...": "Saving...",
  "FLUXO DE RECUPERAÇÃO": "RECOVERY WORKFLOW",
  "Loads e claims": "Loads and claims",
  "registros recentes": "recent records",
  "Carregando loads...": "Loading loads...",
  "Nenhum load registrado. Crie o primeiro para iniciar o fluxo.": "No loads registered. Create the first one to start the workflow.",
  "Origem não informada": "Origin not entered",
  "Destino não informado": "Destination not entered",
  "TERMOS": "TERMS",
  "ROTA": "ROUTE",
  "Registrar chegada": "Record arrival",
  "Registrar saída": "Record departure",
  "Gerar claim": "Generate claim",
  "Gera rascunho calculado": "Creates calculated draft",
  "Rascunho": "Draft",
  "Enviado": "Submitted",
  "Pago": "Paid",
  "Negado": "Denied",
  "Enviar ao broker": "Send to broker",
  "Marcar pago": "Mark paid",
  "Marcar negado": "Mark denied",
  "Uma empresa do Grupo Omega": "An Omega Group company",
  "Recursos": "Features",
  "Planos": "Plans",
  "Para quem é": "Who it is for",
  "Como funciona": "How it works",
  "Suporte 24h": "24/7 support",
  "Teste grátis": "Free trial",
  "Entrar": "Sign in",
  "Biblioteca digital": "Digital library",
  "ACESSO COMPLETO À BIBLIOTECA": "FULL LIBRARY ACCESS",
  "Todos os livros em um único acesso.": "All books in one access.",
  "Por R$ 59,90, tenha uma área exclusiva para baixar as edições em PDF e Kindle que já estiverem disponíveis.": "For R$59.90, get an exclusive area to download the available PDF and Kindle editions.",
  "pagamento único": "one-time payment",
  "Quero ser membro": "Become a member",
  "Já tenho acesso": "I already have access",
  "ESCOLHA SEU TEMA": "CHOOSE YOUR TOPIC",
  "Encontre sua próxima leitura por assunto.": "Find your next read by topic.",
  "Espiritualidade, simbolismo & autoconhecimento": "Spirituality, symbolism & self-knowledge",
  "Tradições, símbolos e reflexões para novas perspectivas.": "Traditions, symbols and reflections for new perspectives.",
  "Saúde & bem-estar": "Health & well-being",
  "Conteúdos sobre hábitos, alimentação e autocuidado.": "Content about habits, nutrition and self-care.",
  "Tecnologia & inovação": "Technology & innovation",
  "Fundamentos e aplicações práticas para acompanhar o presente.": "Foundations and practical applications for today.",
  "Negócios, vendas & finanças": "Business, sales & finance",
  "Persuasão, escolhas financeiras e decisões para avançar.": "Persuasion, financial choices and decisions to move forward.",
  "COLEÇÃO": "COLLECTION",
  "Págs.:": "Pages:",
  "Ver biblioteca": "View library",
  "ÁREA DE MEMBROS": "MEMBER AREA",
  "Todos os livros, em um só lugar.": "All books, in one place.",
  "Faça uma compra única de": "Make a one-time purchase of",
  "e tenha uma área reservada para baixar as edições disponíveis em PDF e Kindle.": "and get a reserved area to download available PDF and Kindle editions.",
  "Todos os livros disponíveis na biblioteca": "All books available in the library",
  "PDF e Kindle · EPUB quando preparados": "PDF and Kindle · EPUB when available",
  "Login próprio, separado do sistema Venda+": "Your own sign-in, separate from the Venda+ business system",
  "Espaço em evolução": "Growing space",
  "Os conteúdos exclusivos da área de membros estão sendo preparados. Por enquanto, seu acesso completo à biblioteca já fica liberado.": "Exclusive member-area content is being prepared. In the meantime, your full library access is already available.",
  "Confirmando seu pagamento…": "Confirming your payment…",
  "ACESSO COMPLETO · R$ 59,90": "FULL ACCESS · R$59.90",
  "Crie seu acesso": "Create your access",
  "Você definirá sua senha agora e entrará automaticamente após a aprovação do pagamento.": "Set your password now and sign in automatically after payment approval.",
  "Crie uma senha": "Create a password",
  "Ao menos 8 caracteres": "At least 8 characters",
  "Confirme a senha": "Confirm password",
  "Repita sua senha": "Repeat your password",
  "Pagamento processado com segurança pelo Mercado Pago.": "Payment securely processed by Mercado Pago.",
  "ENTRAR NA ÁREA": "SIGN IN",
  "Que bom ver você de novo.": "Good to see you again.",
  "Use o e-mail e a senha definidos na compra do acesso completo.": "Use the email and password you set when purchasing full access.",
  "Entrar na área de membros": "Sign in to the member area",
  "Ainda não sou membro": "I am not a member yet",
  "Sua biblioteca está liberada.": "Your library is available.",
  "Baixe as edições que quiser e volte sempre que precisar.": "Download the editions you want and return whenever you need.",
  "livros em sua biblioteca": "books in your library",
  "EM PREPARAÇÃO": "IN PREPARATION",
  "Este espaço vai ganhar mais conteúdos.": "This area will receive more content.",
  "Enquanto isso, todos os livros disponíveis já podem ser baixados abaixo.": "Meanwhile, all available books can already be downloaded below.",
  "Baixar PDF": "Download PDF",
  "Baixar Kindle": "Download Kindle",
  "CONHECIMENTO PARA GUARDAR": "KNOWLEDGE TO KEEP",
  "Livros que despertam novas perguntas.": "Books that awaken new questions.",
  "Conheça páginas selecionadas, escolha o formato e receba o download após a aprovação do Mercado Pago.": "Explore selected pages, choose your format and receive the download after Mercado Pago approves your payment.",
  "Vendas, atendimento, gestão e nota fiscal em uma única operação.": "Sales, customer service, management and tax invoicing in one operation.",
  "O Venda+ conecta atendimento, pedidos, propostas, clientes, estoque, produção, faturamento e emissão fiscal — do comércio às imobiliárias, serviços e estamparias.": "Venda+ connects customer service, orders, proposals, customers, inventory, production, billing and tax invoicing — for retail, real estate, services and print businesses.",
  "Conheça o ERP Venda+": "Discover the Venda+ ERP",
  "gestão integrada": "integrated management",
  "NF-e": "E-invoice",
  "Propostas": "Proposals",
  "Atendimento": "Customer service",
  "Comércio & alimentação": "Retail & food service",
  "atendimento, caixa, pedidos e estoque": "service, checkout, orders and inventory",
  "Serviços & imóveis": "Services & real estate",
  "clientes, propostas, contratos e cobranças": "customers, proposals, contracts and billing",
  "Moda & produção": "Fashion & production",
  "produtos, artes, etapas e prazos": "products, artwork, stages and deadlines",
  "VENDA+ · ERP COMERCIAL E FISCAL": "VENDA+ · COMMERCIAL AND TAX ERP",
  "Sua empresa inteira, conectada em um só sistema.": "Your entire business, connected in one system.",
  "Controle vendas, atendimento, clientes, propostas, estoque, produção, faturamento e NF-e com clareza para decidir e tempo para crescer.": "Manage sales, customer service, customers, proposals, inventory, production, billing and e-invoicing with clarity to decide and time to grow.",
  "Venda e caixa": "Sales and checkout",
  "Estoque e produção": "Inventory and production",
  "Clientes e propostas": "Customers and proposals",
  "Ver tudo o que o Venda+ faz": "See everything Venda+ can do",
  "EXPLORE ANTES DE ESCOLHER": "EXPLORE BEFORE YOU CHOOSE",
  "Uma página certa pode abrir uma ideia inteira.": "The right page can open up a whole idea.",
  "Clique em “Ver páginas” para ampliar uma prévia. A demonstração é protegida e não substitui o livro completo.": "Click “View pages” to expand a preview. The sample is protected and does not replace the complete book.",
  "Ver páginas": "View pages",
  "Em preparação": "Coming soon",
  "SUA COMPRA": "YOUR PURCHASE",
  "Pagamento aprovado. Sua versão PDF está pronta.": "Payment approved. Your PDF edition is ready.",
  "Aguardando a confirmação do Mercado Pago. Esta tela atualiza automaticamente.": "Waiting for Mercado Pago confirmation. This page updates automatically.",
  "Baixar agora": "Download now",
  "PRÉVIA · Venda proibida e reprodução limitada": "PREVIEW · Sale prohibited and reproduction restricted",
  "UMA LEITURA PARA DESPERTAR CURIOSIDADE": "A READING TO SPARK CURIOSITY",
  "Quero em PDF · R$ 11,99": "Get the PDF · R$ 11.99",
  "Quero para Kindle · R$ 39,99": "Get it for Kindle · R$ 39.99",
  "PDF em preparação": "PDF coming soon",
  "Kindle em preparação": "Kindle coming soon",
  "FOLHEIE ANTES DE COMPRAR": "BROWSE BEFORE YOU BUY",
  "Página selecionada": "Selected page",
  "Prévia · Página": "Preview · Page",
  "Arquivo PDF para leitura em celular, computador ou tablet.": "PDF file for reading on a phone, computer or tablet.",
  "EPUB de layout preservado, preparado para enviar ao aplicativo ou dispositivo Kindle.": "Layout-preserved EPUB ready to send to a Kindle app or device.",
  "E-mail para identificar a compra": "Email to identify your purchase",
  "Pagar com Mercado Pago": "Pay with Mercado Pago",
  "Abrindo Stripe...": "Opening Stripe...",
  "Pagar com Stripe": "Pay with Stripe",
  "O download é liberado somente após a confirmação do pagamento.": "The download is released only after payment confirmation.",
  "VENDA+ • CONTROLE MAIS • DECIDA MELHOR": "SELL MORE • CONTROL MORE • DECIDE BETTER",
  "Seu negócio vendendo rápido, com caixa e estoque sob controle.": "Fast sales with cash flow and inventory under control.",
  "Um sistema simples para registrar vendas, acompanhar o que entra e sai e enxergar os números da operação em um só lugar.": "A simple system to record sales, track everything coming in and going out, and see your operation in one place.",
  "Venda sem complicação:": "Simple selling:",
  "PDV direto e rápido": "a fast, straightforward POS",
  "Evite surpresas:": "Avoid surprises:",
  "estoque baixado a cada venda": "inventory updated with every sale",
  "Feche com segurança:": "Close securely:",
  "entradas e retiradas no caixa": "cash deposits and withdrawals",
  "Gerencie de qualquer lugar:": "Manage from anywhere:",
  "computador ou celular": "desktop or mobile",
  "Experimente grátis por 7 dias": "Try it free for 7 days",
  "Cadastre sua empresa sem compromisso. Após nossa liberação, seus 7 dias começam a contar.": "Register your business with no commitment. Your 7 free days start after approval.",
  "Quero testar grátis": "Start my free trial",
  "Suporte quando você precisar": "Support whenever you need it",
  "Atendimento contínuo para orientar sua equipe e acompanhar situações importantes da operação.": "Continuous assistance to guide your team and support important operational situations.",
  "Entre na sua conta": "Sign in to your account",
  "Acesse a operação da sua empresa.": "Access your business operation.",
  "E-mail ou nome de acesso": "Email or username",
  "Senha": "Password",
  "Sua senha": "Your password",
  "Entrando...": "Signing in...",
  "Ainda não tem acesso?": "Don't have access yet?",
  "Solicite seus 7 dias grátis.": "Request your 7 free days.",
  "7 dias grátis": "7-day free trial",
  "para conhecer": "to explore the platform",
  "Dados separados": "Isolated data",
  "por empresa": "for every business",
  "para sua operação": "for your operation",
  "Acesso responsivo": "Responsive access",
  "no celular e computador": "on mobile and desktop",
  "VEJA O VENDA+ EM AÇÃO": "SEE VENDA+ IN ACTION",
  "GESTÃO COMERCIAL E FISCAL BRASILEIRA": "BRAZILIAN COMMERCIAL AND TAX MANAGEMENT",
  "UMA SOLUÇÃO PARA ERP COMERCIAL, DE TRANSPORTE E TRIBUTÁRIO": "A SOLUTION FOR COMMERCIAL, TRANSPORTATION AND TAX ERP DELIVERY",
  "Poder tecnológico sem limites.": "Limitless technological power.",
  "Vendas, atendimento, faturamento e nota fiscal para quem opera no Brasil.": "Sales, customer service, billing and invoicing for businesses operating in Brazil.",
  "Um ERP de vendas, atendimento, faturamento e nota fiscal para quem opera no Brasil.": "An ERP for sales, customer service, billing and invoicing for businesses operating in Brazil.",
  "Um ERP de vendas, atendimento, faturamento e nota fiscal.": "An ERP for sales, customer service, billing and invoicing.",
  "O Venda+ reúne atendimento, PDV, vendas, estoque, faturamento e emissão fiscal em uma única operação. A estrutura tributária é preparada para acompanhar as notas técnicas e as regras da Reforma Tributária, conforme o cronograma oficial de implantação.": "Venda+ brings together customer service, point of sale, sales, inventory, billing and tax issuance in one operation. Its tax structure is designed to follow technical notes and the Brazilian Tax Reform rules according to the official implementation schedule.",
  "O Venda+ é um ERP que reúne atendimento, PDV, vendas, estoque, faturamento e emissão fiscal em uma única operação. A estrutura tributária é preparada para acompanhar as notas técnicas e as regras da Reforma Tributária, conforme o cronograma oficial de implantação.": "Venda+ is an ERP that brings together customer service, point of sale, sales, inventory, billing and tax issuance in one operation. Its tax structure is designed to follow technical notes and the Brazilian Tax Reform rules according to the official implementation schedule.",
  "O Venda+ reúne atendimento automatizado, PDV, vendas, estoque, faturamento e emissão fiscal em uma única operação. A estrutura tributária é preparada para acompanhar as notas técnicas e as regras da Reforma Tributária, conforme o cronograma oficial de implantação.": "Venda+ brings together automated customer service, point of sale, sales, inventory, billing and tax issuance in one operation. Its tax structure is designed to follow technical notes and the Brazilian Tax Reform rules according to the official implementation schedule.",
  "O limite é a nossa imaginação, alinhada às necessidades do seu negócio. Conheça três pontos essenciais de uma operação conectada, simples de entender e pronta para crescer com você.": "The limit is our imagination, aligned with your business needs. Discover three essential parts of a connected operation that is easy to understand and ready to grow with you.",
  "Vendas e atendimento integrados": "Integrated sales and customer service",
  "Atendimento ao cliente automatizado": "Automated customer service",
  "extremamente funcional e customizado: uma IA que responde do seu jeito, como o seu negócio. Nossa responsabilidade é dar tempo e segurança para você.": "extremely functional and customized: an AI that responds your way, just like your business. Our responsibility is to give you time and security.",
  "extremamente funcional, rápido e organizado do primeiro contato ao pós-venda": "extremely functional, fast and organized from the first contact to post-sale",
  "do balcão ao pós-venda, com a equipe trabalhando na mesma informação": "from the counter to post-sale, with the whole team working from the same information",
  "Faturamento sob controle": "Billing under control",
  "Vendas e faturamento sob controle": "Sales and billing under control",
  "PDV, caixa, estoque e indicadores para decidir com dados reais": "point of sale, cash register, inventory and indicators for decisions based on real data",
  "vendas, caixa, estoque e indicadores para decidir com dados reais": "sales, cash register, inventory and indicators for decisions based on real data",
  "Fiscal brasileiro em evolução": "Brazilian tax operations in evolution",
  "Nota Fiscal Eletrônica · NF-e": "Electronic Invoice · NF-e",
  "emissão fiscal e regras tributárias acompanhadas conforme notas técnicas oficiais": "tax issuance and tax rules tracked in line with official technical notes",
  "NF-e, NFS-e e regras tributárias acompanhadas conforme notas técnicas oficiais": "NF-e, NFS-e and tax rules tracked in line with official technical notes",
  "Facilitador da vida": "Making life easier",
  "menos tarefas repetidas e mais tempo para o que importa": "fewer repetitive tasks and more time for what matters",
  "Poder de consciência e comunicação": "The power of awareness and communication",
  "informações claras para toda a equipe trabalhar alinhada": "clear information that keeps the entire team aligned",
  "Poder pessoal": "Personal empowerment",
  "autonomia para compreender, decidir e agir com segurança": "autonomy to understand, decide and act with confidence",
  "Enxergue o negócio inteiro": "See your entire business",
  "Faturamento, vendas, produtos e estoque aparecem juntos. Você entende o que está acontecendo sem depender de várias planilhas ou conferências demoradas.": "Revenue, sales, products and inventory appear together. Understand what is happening without relying on multiple spreadsheets or time-consuming checks.",
  "Venda rápido e atualize tudo": "Sell fast and update everything",
  "O operador registra a venda em poucos passos. No mesmo momento, o caixa recebe a movimentação e o estoque baixa automaticamente.": "The operator records a sale in just a few steps. At the same time, cash flow is updated and inventory is automatically reduced.",
  "Saiba o que entra e o que sai": "Know what comes in and goes out",
  "Consulte saldos, registre entradas e ajustes e identifique itens que precisam de atenção. Mais clareza para comprar melhor e reduzir perdas.": "Check balances, record incoming stock and adjustments, and identify items that need attention. Gain clarity to buy better and reduce losses.",
  "Não é apenas um sistema. É uma visão mais clara da sua empresa.": "It is more than a system. It is a clearer view of your business.",
  "Teste com seus próprios produtos, equipe e rotina durante 7 dias.": "Try it with your own products, team and routine for 7 days.",
  "Quero ver funcionando": "I want to see it working",
  "FEITO PARA QUEM VENDE TODOS OS DIAS": "BUILT FOR BUSINESSES THAT OPERATE EVERY DAY",
  "Varejo e personalizados prontos para operar. Novos segmentos em expansão.": "Retail and custom products ready to operate. New segments are expanding.",
  "Hoje, o Venda+ atende operações de venda, produtos, estoque, caixa, equipe e filiais. Os segmentos marcados como em expansão receberão módulos próprios de CRM, propostas, agenda e processos especializados.": "Today, Venda+ supports sales, products, inventory, cash flow, teams and branches. Segments marked as expanding will receive dedicated CRM, proposal, scheduling and specialized workflow modules.",
  "MÓDULO EM EXPANSÃO": "MODULE IN EXPANSION",
  "Restaurantes": "Restaurants",
  "Registre pedidos e acompanhe vendas, produtos e movimentações do dia.": "Record orders and track daily sales, products and transactions.",
  "Bares": "Bars",
  "Ganhe velocidade no atendimento e veja o estoque baixar automaticamente.": "Serve faster while inventory updates automatically.",
  "Adegas": "Wine and beverage stores",
  "Controle variedade, quantidade, preços e acesso da equipe em uma única tela.": "Control assortment, quantities, prices and team access in one place.",
  "Lojas": "Retail stores",
  "Centralize catálogo, caixa, filiais e indicadores para decidir com mais clareza.": "Centralize catalog, cash flow, branches and indicators for clearer decisions.",
  "Advogados e contratos": "Law firms and contracts",
  "Organize serviços, responsáveis, recebimentos e acessos conforme o fluxo do escritório.": "Organize services, owners, payments and access according to your firm's workflow.",
  "Consultórios": "Clinics and practices",
  "Acompanhe serviços, recebimentos, equipe e unidades em um ambiente centralizado.": "Track services, payments, teams and locations in one centralized environment.",
  "Materiais para construção": "Building supply stores",
  "Controle um catálogo amplo, movimentações de estoque, caixa e diferentes usuários.": "Control a broad catalog, inventory movements, cash flow and different users.",
  "Locadoras de veículos": "Vehicle rental companies",
  "Adapte cadastros, cobranças, responsáveis e filiais ao processo da sua operação.": "Adapt records, payments, owners and branches to your operational process.",
  "Imobiliárias e corretores": "Real estate agencies and brokers",
  "Centralize imóveis, empreendimentos, clientes, corretores, visitas e propostas para acompanhar cada oportunidade até o fechamento.": "Centralize properties, developments, clients, brokers, visits and proposals to track every opportunity through closing.",
  "Estamparias": "Print shops",
  "Organize pedidos, artes, produtos, etapas de produção, prazos e entregas em uma operação personalizada.": "Organize orders, artwork, products, production stages, deadlines and deliveries in a customized operation.",
  "CONTROLE QUE GERA VALOR": "CONTROL THAT CREATES VALUE",
  "Transforme cada venda em informação para decidir melhor.": "Turn every sale into information for better decisions.",
  "O Venda+ reúne a operação em painéis simples: o caixa registra, o estoque acompanha, a gestão compara e você controla acessos, filiais e resultados de onde estiver.": "Venda+ brings your operation into simple dashboards: cash is recorded, inventory is tracked, management compares results, and you control access and branches from anywhere.",
  "em vendas acompanhadas por mês": "in monthly tracked sales",
  "de valor potencialmente preservado": "in potentially preserved value",
  "liberadas no fechamento mensal": "saved during monthly closing",
  "Os números são exemplos ilustrativos e não representam garantia de faturamento ou economia.": "These figures are illustrative examples and do not guarantee revenue or savings.",
  "Venda e recebimento": "Sales and payments",
  "Gestão por painéis": "Dashboard management",
  "Controle operacional": "Operational control",
  "Acesso seguro": "Secure access",
  "Suporte 24 horas": "24/7 support",
  "Em qualquer tela": "On every screen",
  "DA VENDA À DECISÃO": "FROM TRANSACTION TO DECISION",
  "Tudo conectado para você trabalhar com menos retrabalho.": "Everything connected so your team does less repetitive work.",
  "Registre a venda": "Record the transaction",
  "Atualize o estoque": "Update inventory",
  "Acompanhe o caixa": "Track cash flow",
  "Decida pelos números": "Decide with data",
  "CONTROLE SEM PRENDER VOCÊ AO BALCÃO": "CONTROL WITHOUT BEING TIED TO THE COUNTER",
  "Veja sua operação de onde estiver.": "See your operation from anywhere.",
  "PAINEL EM TEMPO REAL": "REAL-TIME DASHBOARD",
  "Vendas + Estoque + Caixa": "Sales + Inventory + Cash",
  "Começar meus 7 dias grátis": "Start my 7 free days",
  "PERGUNTAS FREQUENTES": "FREQUENTLY ASKED QUESTIONS",
  "Comece com tranquilidade.": "Get started with confidence.",
  "Preciso instalar alguma coisa?": "Do I need to install anything?",
  "Não. O Venda+ funciona pelo navegador no computador, tablet ou celular.": "No. Venda+ runs in your browser on desktop, tablet or mobile.",
  "Quando começam os 7 dias grátis?": "When do my 7 free days start?",
  "Meus dados ficam misturados com os de outra empresa?": "Is my data mixed with another company's data?",
  "Não. Cada empresa possui ambiente, usuários, dados e configurações independentes.": "No. Each business has its own environment, users, data and settings.",
  "Consigo controlar quem acessa o sistema?": "Can I control who accesses the system?",
  "Sim. Você cria usuários e define funções como administrador, gerente, caixa ou estoque.": "Yes. Create users and assign roles such as administrator, manager, cashier or inventory.",
  "PRONTO PARA ORGANIZAR SUA OPERAÇÃO?": "READY TO ORGANIZE YOUR OPERATION?",
  "Teste o Venda+ gratuitamente por 7 dias.": "Try Venda+ free for 7 days.",
  "Quero testar o Venda+": "I want to try Venda+",
  "Sem cobrança para solicitar o teste.": "No charge to request your trial.",
  "PLANOS SIMPLES E SUPORTE 24H": "SIMPLE PLANS AND 24/7 SUPPORT",
  "Escolha somente depois de testar.": "Choose only after your trial.",
  "O cadastro e os 7 dias de teste são gratuitos. Você não paga nada agora. Conheça o sistema primeiro e escolha o plano mais adequado depois.": "Registration and the 7-day trial are free. You pay nothing now. Explore the system first and choose the best plan afterward.",
  "PARA COMEÇAR": "TO GET STARTED",
  "PARA CRESCER": "TO GROW",
  "PARA EXPANDIR": "TO EXPAND",
  "PRA COMEÇAR": "TO GET STARTED",
  "PRA CRESCER": "TO GROW",
  "PRA EXPANDIR": "TO EXPAND",
  "Essencial": "Essential",
  "Escala": "Scale",
  "/mês": "/month",
  "Para uma operação menor que precisa organizar vendas, produtos, estoque, caixa e indicadores.": "For a smaller operation that needs to organize sales, products, inventory, cash control and indicators.",
  "Para negócios em crescimento que precisam organizar melhor equipe, filiais e gestão.": "For growing businesses that need better organization for teams, branches and management.",
  "Para operações mais complexas, com várias equipes ou unidades e estrutura preparada para expansão.": "For more complex operations with multiple teams or locations and an expansion-ready structure.",
  "PDV e formas de pagamento": "POS and payment methods",
  "PDV, vendas e formas de pagamento": "POS, sales and payment methods",
  "Produtos e estoque conectado": "Products and connected inventory",
  "Abertura e fechamento de caixa": "Cash opening and closing",
  "Abertura, movimentação e fechamento de caixa": "Cash opening, transactions and closing",
  "Painel com os principais números": "Dashboard with key figures",
  "Painel com os principais indicadores": "Dashboard with key indicators",
  "1 filial e até 3 usuários": "1 branch and up to 3 users",
  "Até 3 filiais e 10 usuários": "Up to 3 branches and 10 users",
  "Até 10 filiais e 50 usuários": "Up to 10 branches and 50 users",
  "Perfis, permissões e controles administrativos": "Roles, permissions and administrative controls",
  "Painéis gerenciais e suporte prioritário": "Management dashboards and priority support",
  "Acompanhamento dedicado para expansão": "Dedicated guidance for expansion",
  "Incluído": "Included",
  "Não incluído": "Not included",
  "Rotina de vendas, estoque e caixa": "Sales, inventory and cash routines",
  "Usuários separados por função": "Users separated by role",
  "Organização por filiais": "Branch organization",
  "Controles administrativos ampliados": "Extended administrative controls",
  "Gestão centralizada da operação": "Centralized operation management",
  "Equipes, permissões e filiais": "Teams, permissions and branches",
  "Monitoramento administrativo": "Administrative monitoring",
  "Histórico para maior controle": "History for greater control",
  "Sem cobrança no cadastro. Valores mensais dos planos após o período gratuito.": "No charge upon registration. Monthly plan prices apply after the free period.",
  "Visão geral": "Overview",
  "RESUMO DO PROPRIETÁRIO · HOJE": "OWNER SUMMARY · TODAY",
  "Seu negócio em poucos segundos": "Your business in a few seconds",
  "Faturamento hoje": "Revenue today",
  "Ticket médio": "Average ticket",
  "ATENÇÃO AGORA": "NEEDS ATTENTION",
  "6 produtos precisam de reposição": "6 products need restocking",
  "Ver estoque →": "View inventory →",
  "O limite é a nossa imaginação, alinhada às necessidades do seu negócio. Veja exemplos práticos de vendas do dia, desempenho semanal, estoque e um fluxo de entregas que pode ser configurado para sua operação.": "Our imagination, aligned with your business needs, is the limit. See practical examples of daily sales, weekly performance, inventory and a delivery workflow that can be configured for your operation.",
  "Vendas · Hoje": "Sales · Today",
  "FATURAMENTO HOJE": "REVENUE TODAY",
  "98 vendas": "98 sales",
  "Pico de vendas: 18h": "Sales peak: 6 PM",
  "R$ 820 no período": "R$ 820 in the period",
  "01 · VENDAS DO DIA": "01 · DAILY SALES",
  "Descubra os horários que mais vendem": "Discover your strongest sales hours",
  "O gráfico diário mostra a evolução das vendas por horário, o faturamento, o ticket médio e o pico do dia. Exemplo: às 18h foram vendidos R$ 820, ajudando a planejar equipe e reposição.": "The daily chart shows sales by hour, revenue, average ticket and the day's peak. In this example, R$ 820 was sold at 6 PM, helping plan staffing and restocking.",
  "Vendas · Semana": "Sales · Week",
  "FATURAMENTO SEMANAL": "WEEKLY REVENUE",
  "+12,4% sobre a semana anterior": "+12.4% over the previous week",
  "642 vendas": "642 sales",
  "Melhor dia: sábado": "Best day: Saturday",
  "R$ 4.920 em vendas": "R$ 4,920 in sales",
  "02 · VISÃO SEMANAL": "02 · WEEKLY VIEW",
  "Compare resultados e reconheça tendências": "Compare results and recognize trends",
  "A visão semanal permite comparar cada dia e perceber crescimento ou queda. No exemplo, sábado faturou R$ 4.920 e a semana cresceu 12,4% em relação à anterior.": "The weekly view compares each day and reveals growth or decline. In this example, Saturday generated R$ 4,920 and the week grew 12.4% over the previous one.",
  "03 · ESTOQUE": "03 · INVENTORY",
  "Reponha antes que o produto acabe": "Restock before products run out",
  "Consulte saldos, registre entradas e ajustes e identifique itens em atenção. No exemplo, a Heineken chegou a 18 unidades e já aparece destacada para reposição.": "Review balances, record incoming stock and adjustments, and identify items needing attention. In this example, Heineken reached 18 units and is highlighted for restocking.",
  "Entregas · Hoje": "Deliveries · Today",
  "PEDIDOS DE HOJE": "TODAY'S ORDERS",
  "24 entregas": "24 deliveries",
  "CONCLUÍDAS": "COMPLETED",
  "EM ROTA": "ON ROUTE",
  "AGUARDANDO": "WAITING",
  "Em rota": "On route",
  "Preparando": "Preparing",
  "Entregue": "Delivered",
  "Fluxo configurável conforme sua operação": "Workflow configurable for your operation",
  "04 · ENTREGAS CONFIGURÁVEIS": "04 · CONFIGURABLE DELIVERIES",
  "Saiba o que está parado, em rota ou entregue": "Know what is waiting, on route or delivered",
  "Um fluxo configurável pode reunir pedido, cliente, região, previsão e situação da entrega. Assim, a equipe responde com clareza e o gestor identifica atrasos antes da reclamação.": "A configurable workflow can bring together the order, customer, region, estimated time and delivery status. This helps the team respond clearly and lets managers identify delays before complaints arrive.",
  "Dados demonstrativos para exemplificar a leitura dos painéis. O fluxo de entregas é configurável e ainda não integra o módulo operacional padrão.": "Demonstration data illustrating how the dashboards are read. The delivery workflow is configurable and is not yet part of the standard operational module.",
  "Ver detalhes": "View details",
  "Salão:": "Dine-in:",
  "Delivery:": "Delivery:",
  "Retirada:": "Pickup:",
  "52% das vendas": "52% of sales",
  "31% das vendas": "31% of sales",
  "17% das vendas": "17% of sales",
  "Melhor dia:": "Best day:",
  "sábado": "Saturday",
  "Ticket médio:": "Average ticket:",
  "Planejamento:": "Planning:",
  "reforce a equipe de sexta a domingo": "increase staffing from Friday through Sunday",
  "Reposição:": "Restocking:",
  "6 produtos em atenção": "6 products need attention",
  "Cobertura:": "Coverage:",
  "quantidade disponível para o próximo turno": "available quantity for the next shift",
  "Conferência:": "Reconciliation:",
  "entradas, vendas e ajustes no mesmo histórico": "incoming stock, sales and adjustments in one history",
  "Tempo médio:": "Average time:",
  "32 minutos": "32 minutes",
  "No prazo:": "On time:",
  "92% das entregas": "92% of deliveries",
  "Ação imediata:": "Immediate action:",
  "2 pedidos aguardam saída": "2 orders are waiting to leave",
  "Saiba onde agir antes de perder venda": "Know where to act before losing a sale",
  "Veja quanto entrou hoje, o valor médio de cada venda e quais produtos precisam de reposição. Informação pronta para decidir sem depender de várias planilhas.": "See today's revenue, the average value of each sale and which products need restocking. Decision-ready information without relying on multiple spreadsheets.",
  "Caixa": "Cash register",
  "Estoque": "Inventory",
  "Produtos": "Products",
  "Usuários": "Users",
  "Filial": "Branch",
  "Fiscal": "Tax",
  "EMPRESA ATUAL": "CURRENT BUSINESS",
  "Alterar minha senha": "Change my password",
  "Sair": "Sign out",
  "AMBIENTE DE DEMONSTRAÇÃO": "DEMO ENVIRONMENT",
  "Caixa aberto": "Cash register open",
  "Caixa fechado": "Cash register closed",
  "Operação conectada": "Connected operation",
  "Faturamento": "Revenue",
  "Vendas": "Sales",
  "Itens em estoque": "Items in inventory",
  "Produtos cadastrados": "Registered products",
  "Novo produto": "New product",
  "Produto": "Product",
  "Preço": "Price",
  "Quantidade": "Quantity",
  "Cadastro": "Created",
  "Cadastrar produto": "Add product",
  "Abrir caixa": "Open cash register",
  "Fechar caixa": "Close cash register",
  "Registrar movimento": "Record movement",
  "Forma de pagamento": "Payment method",
  "Finalizar venda": "Complete sale",
  "Dinheiro": "Cash",
  "Crédito": "Credit card",
  "Débito": "Debit card",
  "Nome": "Name",
  "Confirmar": "Confirm",
  "Salvar": "Save",
  "Fechar": "Close",
  "Voltar": "Back",
  "Cancelar": "Cancel",
  "Carregando...": "Loading...",
  "Criar teste gratuito": "Create free trial",
  "Voltar ao login": "Back to sign in",
  "Teste grátis por 7 dias": "Free 7-day trial",
  "Personalize a plataforma para sua empresa.": "Customize the platform for your business.",
  "Crie sua conta": "Create your account",
  "Empresa": "Business",
  "Segmento": "Industry",
  "Restaurante": "Restaurant",
  "Adega": "Wine store",
  "Loja/varejo": "Retail store",
  "Confecção e personalizados": "Apparel and custom products",
  "Cidade": "City",
  "UF": "State",
  "Responsável": "Account owner",
  "E-mail": "Email",
  "CONFIGURAÇÃO GUIADA": "GUIDED SETUP",
  "Pular por agora": "Skip for now",
  "Configure a empresa": "Configure your business",
  "Cadastre o primeiro produto": "Add your first product",
  "Abra o caixa": "Open the cash register",
  "Faça a primeira venda": "Complete your first sale",
  "Salvar empresa": "Save business",
  "Escolha um produto": "Choose a product",
  "Concluir primeira venda": "Complete first sale",
  "Configuração concluída!": "Setup complete!",
  "Entrar no painel": "Open dashboard",
  "ASSINATURA VENDA+": "VENDA+ SUBSCRIPTION",
  "Plano mensal": "Monthly plan",
  "Mensal": "Monthly",
  "Semestral": "Semiannual",
  "Anual": "Annual",
  "Economize 20%": "Save 20%",
  "Economize 30%": "Save 30%",
  "20% de desconto": "20% discount",
  "30% de desconto": "30% discount",
  "Escolha o plano e o período. O acesso é liberado após a confirmação do Mercado Pago.": "Choose your plan and billing period. Access is released after Mercado Pago confirms the payment.",
  "Pix e boleto são pagos pelo total do período. No cartão, o Mercado Pago poderá oferecer até 1 parcela(s), sujeito à aprovação.": "Pix and boleto are paid for the full period. For cards, Mercado Pago may offer 1 installment, subject to approval.",
  "Pix e boleto são pagos pelo total do período. No cartão, o Mercado Pago poderá oferecer até 6 parcela(s), sujeito à aprovação.": "Pix and boleto are paid for the full period. For cards, Mercado Pago may offer up to 6 installments, subject to approval.",
  "Pix e boleto são pagos pelo total do período. No cartão, o Mercado Pago poderá oferecer até 12 parcela(s), sujeito à aprovação.": "Pix and boleto are paid for the full period. For cards, Mercado Pago may offer up to 12 installments, subject to approval.",
  "Sem cobrança no cadastro. Planos semestrais e anuais são cobrados pelo período escolhido; no cartão, o parcelamento depende da aprovação do Mercado Pago.": "No charge upon registration. Semiannual and annual plans are charged for the selected period; card installments depend on Mercado Pago approval.",
  "E-mail do pagador": "Payer email",
  "Continuar para pagamento": "Continue to payment",
  "Abrindo Mercado Pago...": "Opening Mercado Pago...",
  "Voltar ao Venda+": "Back to Venda+",
  "ADMINISTRAÇÃO DA PLATAFORMA": "PLATFORM ADMINISTRATION",
  "Monitor de clientes": "Customer monitor",
  "Novo usuário": "New user",
  "Tela inicial": "Home",
  "Buscar cliente": "Search customers",
  "Total": "Total",
  "Em teste": "On trial",
  "Ativos": "Active",
  "Expirados": "Expired",
  "Aguardando aprovação": "Awaiting approval",
  "Gerenciar cliente": "Manage customer",
  "Ajustar dias de teste": "Adjust trial days",
  "Ativar plano": "Activate plan",
  "Liberar 7 dias grátis": "Approve 7 free days",
  "Gerar pagamento": "Create payment",
  "Ativar conta": "Activate account",
  "Voltar para teste": "Return to trial",
  "Suspender acesso": "Suspend access",
  "Dados cadastrais": "Registration data",
  "Controle da conta": "Account control",
  "Filiais": "Branches",
  "Histórico administrativo": "Administrative history",
  "PENDENTE": "PENDING",
  "ATIVO": "ACTIVE",
  "EXPIRADO": "EXPIRED",
  "SUSPENSO": "SUSPENDED",
};

const dynamic: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
  [/^Você ainda tem (\d+) dia grátis\.$/, (m) => `You still have ${m[1]} free day.`],
  [/^Você ainda tem (\d+) dias grátis\.$/, (m) => `You still have ${m[1]} free days.`],
  [/^(\d+) produtos cadastrados$/, (m) => `${m[1]} registered products`],
  [/^(\d+) de 4 etapas concluídas$/, (m) => `${m[1]} of 4 steps completed`],
  [/^Vamos preparar (.+)$/, (m) => `Let's set up ${m[1]}`],
  [/^Vencimento: (.+)$/, (m) => `Expires: ${m[1]}`],
];

const originals = new WeakMap<Node, string>();
const attributeOriginals = new WeakMap<Element, Map<string, string>>();

function translated(value: string) {
  const exact = english[value];
  if (exact) return exact;
  for (const [pattern, output] of dynamic) {
    const match = value.match(pattern);
    if (match) return output(match);
  }
  return value;
}

function translateNode(root: Node, locale: Locale, captureChanges = false) {
  const nodes: Node[] = [root];
  while (nodes.length) {
    const node = nodes.pop()!;
    if (node.nodeType === Node.TEXT_NODE) {
      const current = node.textContent ?? "";
      if (!current.trim()) continue;
      if (captureChanges && originals.has(node)) {
        const saved = originals.get(node)!;
        const savedTrimmed = saved.trim();
        const expected = saved.replace(
          savedTrimmed,
          locale === "en" ? translated(savedTrimmed) : savedTrimmed,
        );
        if (current !== expected) originals.set(node, current);
      }
      if (!originals.has(node)) originals.set(node, current);
      const original = originals.get(node)!;
      const trimmed = original.trim();
      const replacement = locale === "en" ? translated(trimmed) : trimmed;
      const next = original.replace(trimmed, replacement);
      if (node.textContent !== next) node.textContent = next;
      continue;
    }
    if (node instanceof Element) {
      for (const attribute of ["placeholder", "title", "aria-label"]) {
        const current = node.getAttribute(attribute);
        if (!current) continue;
        let saved = attributeOriginals.get(node);
        if (!saved) {
          saved = new Map();
          attributeOriginals.set(node, saved);
        }
        if (!saved.has(attribute)) saved.set(attribute, current);
        const original = saved.get(attribute)!;
        node.setAttribute(attribute, locale === "en" ? translated(original) : original);
      }
      nodes.push(...Array.from(node.childNodes));
    }
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState<Locale>("pt-BR");
  const [hasSession, setHasSession] = useState(false);
  useEffect(() => {
    const saved = localStorage.getItem("vendamais-language") as Locale | null;
    const detected = navigator.language.toLowerCase().startsWith("pt") ? "pt-BR" : "en";
    const initial = saved === "pt-BR" || saved === "en" ? saved : detected;
    localStorage.setItem("vendamais-language", initial);
    setLocale(initial);
  }, []);
  useEffect(() => {
    const syncSession = () => setHasSession(Boolean(localStorage.getItem("varejo-session")));
    syncSession();
    window.addEventListener("storage", syncSession);
    const timer = window.setInterval(syncSession, 1_000);
    return () => {
      window.removeEventListener("storage", syncSession);
      window.clearInterval(timer);
    };
  }, []);
  useEffect(() => {
    document.documentElement.lang = locale;
    document.cookie = `vendamais-language=${locale};path=/;max-age=31536000;SameSite=Lax`;
    translateNode(document.body, locale);
    // Do not observe React-managed content. Mutating chat/dashboard nodes while
    // React reconciles them can invalidate its references and crash the page.
  }, [locale]);
  useEffect(() => {
    const translateNewContent = () => translateNode(document.body, locale, true);
    window.addEventListener("vendamais-translate-content", translateNewContent);
    return () => window.removeEventListener("vendamais-translate-content", translateNewContent);
  }, [locale]);
  const choose = (next: Locale) => {
    localStorage.setItem("vendamais-language", next);
    window.dispatchEvent(new CustomEvent("vendamais-language-change", { detail: next }));
    setLocale(next);
  };
  return <>{children}{hasSession&&<button className="mobile-logout" onClick={()=>{localStorage.removeItem("varejo-session");location.replace("/")}}>{locale === "en" ? "Sign out" : "Sair"}</button>}<div className="language-switcher" style={{ position: "fixed", top: 12, right: 12, bottom: "auto" }} role="group" aria-label="Idioma / Language"><button className={locale === "pt-BR" ? "active" : ""} onClick={() => choose("pt-BR")} aria-label="Português">PT</button><button className={locale === "en" ? "active" : ""} onClick={() => choose("en")} aria-label="English">EN</button></div></>;
}
