"use client";
import { FormEvent, useEffect, useState } from "react";
import { request } from "./api-client";

type Option={id:string;name:string;active?:boolean;price?:number;kind?:"ADDITION"|"REMOVAL";maxFlavors?:number;serves?:number};
type Configuration={enabled:boolean;pricingRule:"HIGHEST_PRICE"|"AVERAGE"|"PROPORTIONAL";sizes:Option[];flavors:Option[];doughs:Option[];crusts:Option[];modifiers:Option[];pizzas:Array<{id:string;name:string;sku:string;sizes:Array<Option>;flavors:Array<Option>}>};
const labels:Record<Configuration["pricingRule"],string>={HIGHEST_PRICE:"Sabor de maior valor",AVERAGE:"Média dos sabores",PROPORTIONAL:"Cálculo proporcional"};

export function Pizzeria({token}:{token:string}){
  const [data,setData]=useState<Configuration|null>(null),[message,setMessage]=useState(""),[error,setError]=useState("");
  const load=async()=>{try{setData(await request<Configuration>("/pizzeria/configuration",token));setError("")}catch(cause){setError((cause as Error).message)}};
  useEffect(()=>{void load()},[token]);
  const send=async(path:string,body:unknown)=>{try{await request(path,token,{method:"POST",body:JSON.stringify(body)});setMessage("Configuração salva.");await load()}catch(cause){setError((cause as Error).message)}};
  if(!data)return <p>Carregando configurações da pizzaria…</p>;
  if(!data.enabled)return <section className="pizzeria-panel"><small>MÓDULO OPCIONAL</small><h2>Ative a operação para pizzaria.</h2><p>Produtos, pedidos e estoque atuais não são alterados. Ao ativar, a empresa passa a ter tamanhos, sabores, massas, bordas e regras de preço próprias.</p><button onClick={async()=>{try{await request("/pizzeria/module",token,{method:"PUT",body:JSON.stringify({enabled:true})});setMessage("Módulo Pizzaria ativado.");await load()}catch(cause){setError((cause as Error).message)}}}>Ativar Pizzaria</button>{error&&<p className="error">{error}</p>}</section>;
  return <section className="pizzeria-panel"><header><div><small>PIZZARIA · FASE 1</small><h2>Cardápio e regras de pizza</h2><p>Cadastre primeiro os componentes e depois monte as pizzas. O cálculo de preço permanece no servidor.</p></div><label>Regra de multi-sabor<select value={data.pricingRule} onChange={async e=>{try{await request("/pizzeria/pricing-rule",token,{method:"PUT",body:JSON.stringify({pricingRule:e.target.value})});await load()}catch(cause){setError((cause as Error).message)}}}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></header>
    {message&&<p className="success">{message}</p>}{error&&<p className="error">{error}</p>}
    <div className="pizzeria-grid">
      <PizzaSizeForm onSave={body=>send("/pizzeria/sizes",body)} items={data.sizes}/>
      <NamedForm title="Sabores" placeholder="Ex.: Calabresa" items={data.flavors} onSave={body=>send("/pizzeria/flavors",body)}/>
      <NamedForm title="Massas" placeholder="Ex.: Tradicional" items={data.doughs} onSave={body=>send("/pizzeria/doughs",body)}/>
      <NamedForm title="Bordas" placeholder="Ex.: Catupiry" items={data.crusts} onSave={body=>send("/pizzeria/crusts",body)}/>
      <ModifierForm items={data.modifiers} onSave={body=>send("/pizzeria/modifiers",body)}/>
    </div>
    <PizzaForm sizes={data.sizes} flavors={data.flavors} onSave={body=>send("/pizzeria/pizzas",body)} />
    {data.pizzas.length>0&&<div className="pizzeria-list"><h3>Pizzas cadastradas</h3>{data.pizzas.map(pizza=><article key={pizza.id}><b>{pizza.name}</b><span>{pizza.sizes.map(size=>size.name).join(", ")}</span><span>{pizza.flavors.map(flavor=>flavor.name).join(", ")}</span></article>)}</div>}
  </section>;
}
function NamedForm({title,placeholder,items,onSave}:{title:string;placeholder:string;items:Option[];onSave:(body:{name:string})=>void}){return <article className="pizzeria-card"><h3>{title}</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:String(f.get("name"))});e.currentTarget.reset()}}><input name="name" placeholder={placeholder} minLength={2} required/><button>Adicionar</button></form><p>{items.map(item=>item.name).join(" · ")||"Nenhum cadastro"}</p></article>}
function PizzaSizeForm({items,onSave}:{items:Option[];onSave:(body:{name:string;maxFlavors:number;serves?:number})=>void}){return <article className="pizzeria-card"><h3>Tamanhos</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:String(f.get("name")),maxFlavors:Number(f.get("maxFlavors")),serves:f.get("serves")?Number(f.get("serves")):undefined});e.currentTarget.reset()}}><input name="name" placeholder="Ex.: Grande" minLength={2} required/><label>Máx. sabores<input name="maxFlavors" type="number" min="1" max="4" defaultValue="2" required/></label><label>Pessoas<input name="serves" type="number" min="1" max="30"/></label><button>Adicionar</button></form><p>{items.map(item=>`${item.name} · até ${item.maxFlavors} sabor(es)`).join(" | ")||"Nenhum cadastro"}</p></article>}
function ModifierForm({items,onSave}:{items:Option[];onSave:(body:{name:string;kind:"ADDITION"|"REMOVAL";price:number})=>void}){return <article className="pizzeria-card"><h3>Adicionais e remoções</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:String(f.get("name")),kind:String(f.get("kind")) as "ADDITION"|"REMOVAL",price:Number(f.get("price"))});e.currentTarget.reset()}}><input name="name" placeholder="Ex.: Bacon" minLength={2} required/><select name="kind"><option value="ADDITION">Adicional</option><option value="REMOVAL">Remoção</option></select><input name="price" type="number" min="0" step="0.01" defaultValue="0" required/><button>Adicionar</button></form><p>{items.map(item=>`${item.name} (${item.kind==="ADDITION"?"adicional":"remoção"})`).join(" · ")||"Nenhum cadastro"}</p></article>}
function PizzaForm({sizes,flavors,onSave}:{sizes:Option[];flavors:Option[];onSave:(body:unknown)=>void}){if(!sizes.length||!flavors.length)return <p className="pizzeria-hint">Cadastre ao menos um tamanho e um sabor para montar uma pizza.</p>;return <article className="pizzeria-card pizzeria-create"><h3>Montar pizza</h3><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({sku:String(f.get("sku")),name:String(f.get("name")),sizes:sizes.map(size=>({sizeId:size.id,price:Number(f.get(`size-${size.id}`))})),flavors:flavors.map(flavor=>({flavorId:flavor.id,price:Number(f.get(`flavor-${flavor.id}`))}))});}}><input name="sku" placeholder="SKU" minLength={2} required/><input name="name" placeholder="Nome da pizza" minLength={2} required/><div><b>Preço base por tamanho</b>{sizes.map(size=><label key={size.id}>{size.name}<input name={`size-${size.id}`} type="number" min="0" step="0.01" defaultValue="0" required/></label>)}</div><div><b>Acréscimo por sabor</b>{flavors.map(flavor=><label key={flavor.id}>{flavor.name}<input name={`flavor-${flavor.id}`} type="number" min="0" step="0.01" defaultValue="0" required/></label>)}</div><button>Cadastrar pizza</button></form></article>}
