import { BadGatewayException, BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { prisma } from "@varejo/database";
import { randomUUID } from "node:crypto";
@Injectable()
export class BillingService{
  private token(){const value=process.env.MERCADO_PAGO_ACCESS_TOKEN;if(!value)throw new BadRequestException("Pagamento temporariamente indisponível: Mercado Pago não configurado");return value}
  private price(){const value=Number(process.env.PLATFORM_MONTHLY_PRICE);if(!Number.isFinite(value)||value<=0)throw new BadRequestException("Valor do plano ainda não configurado");return Number(value.toFixed(2))}
  async publicInfo(tenantId:string){const tenant=await prisma.tenant.findUnique({where:{id:tenantId},select:{id:true,name:true,status:true}});if(!tenant)throw new NotFoundException("Empresa não encontrada");return{...tenant,amount:this.price(),methods:["PIX","Cartão de crédito","Cartão de débito","Boleto"]}}
  async checkout(tenantId:string,email?:string){const tenant=await prisma.tenant.findUnique({where:{id:tenantId},select:{id:true,name:true}});if(!tenant)throw new NotFoundException("Empresa não encontrada");const amount=this.price(),externalReference=randomUUID(),base=(process.env.PUBLIC_APP_URL??"https://www.vendamais-app.com").replace(/\/$/,"");const payment=await prisma.billingPayment.create({data:{tenantId,externalReference,amount}});const response=await fetch("https://api.mercadopago.com/checkout/preferences",{method:"POST",headers:{Authorization:`Bearer ${this.token()}`,"Content-Type":"application/json","X-Idempotency-Key":externalReference},body:JSON.stringify({items:[{id:"vendamais-mensal",title:`Venda+ - Plano mensal - ${tenant.name}`,description:"Sistema de vendas e gestão de estoque",quantity:1,currency_id:"BRL",unit_price:amount}],payer:email?{email}:undefined,external_reference:externalReference,notification_url:`${base}/api/billing/webhook`,back_urls:{success:`${base}/pagamento?cliente=${tenantId}&resultado=sucesso`,pending:`${base}/pagamento?cliente=${tenantId}&resultado=pendente`,failure:`${base}/pagamento?cliente=${tenantId}&resultado=falha`},auto_return:"approved",statement_descriptor:"VENDAMAIS"})});const data=await response.json().catch(()=>({}));if(!response.ok){await prisma.billingPayment.update({where:{id:payment.id},data:{status:"ERROR"}});throw new BadGatewayException(data?.message??"Mercado Pago não iniciou o pagamento")}const checkoutUrl=process.env.MERCADO_PAGO_SANDBOX==="true"?data.sandbox_init_point:data.init_point;await prisma.billingPayment.update({where:{id:payment.id},data:{preferenceId:data.id,checkoutUrl}});return{checkoutUrl,externalReference}}
  async webhook(paymentId:string){if(!paymentId)return{received:true};const response=await fetch(`https://api.mercadopago.com/v1/payments/${encodeURIComponent(paymentId)}`,{headers:{Authorization:`Bearer ${this.token()}`}});if(!response.ok)throw new BadGatewayException("Não foi possível validar o pagamento");const data=await response.json(),reference=String(data.external_reference??"");const payment=await prisma.billingPayment.findUnique({where:{externalReference:reference}});if(!payment)return{received:true};if(Number(data.transaction_amount)!==Number(payment.amount))throw new BadRequestException("Valor do pagamento não confere");const approved=data.status==="approved";await prisma.$transaction([prisma.billingPayment.update({where:{id:payment.id},data:{providerPaymentId:String(data.id),status:String(data.status).toUpperCase(),paymentMethod:String(data.payment_type_id??data.payment_method_id??""),paidAt:approved?new Date(data.date_approved??Date.now()):null}}),...(approved?[prisma.tenant.update({where:{id:payment.tenantId},data:{status:"ACTIVE"}})]:[])]);return{received:true}}
}
