import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { calculateFlavorPrice } from "./pizza-pricing";

type Rule="HIGHEST_PRICE"|"AVERAGE"|"PROPORTIONAL";
type Option={id:string;name:string;active:boolean;price?:number;kind?:"ADDITION"|"REMOVAL";maxFlavors?:number;serves?:number};
type Pizza={id:string;productId:string;name:string;sku:string;active:boolean;sizes:Option[];flavors:Option[];modifiers:Option[]};
type Order={id:string;number:number;status:string;serviceType:string;paymentState:string;customerId?:string;customerName?:string;customerPhone?:string;address?:string;notes?:string;total:number;createdAt:string;items:Array<{id:string;pizzaProductId:string;name:string;quantity:number;unitPrice:number;total:number;selection:any}>};
type TenantData={enabled:boolean;pricingRule:Rule;sizes:Option[];flavors:Option[];doughs:Option[];crusts:Option[];modifiers:Option[];pizzas:Pizza[];orders:Order[]};
type Data=Record<string,TenantData>;
const fresh=():TenantData=>({enabled:false,pricingRule:"HIGHEST_PRICE",sizes:[],flavors:[],doughs:[],crusts:[],modifiers:[],pizzas:[],orders:[]});

@Injectable()
export class PizzeriaDemoStore {
  private readonly file=resolve(process.cwd(),"../../storage/pizzeria-demo.json");
  private data:Data=this.load();
  private load(){try{return JSON.parse(readFileSync(this.file,"utf8")) as Data}catch{return{}}}
  private save(){mkdirSync(dirname(this.file),{recursive:true});writeFileSync(this.file,JSON.stringify(this.data,null,2))}
  private tenant(id:string){return this.data[id]??(this.data[id]=fresh())}
  configuration(tenantId:string){const d=this.tenant(tenantId);return{enabled:d.enabled,pricingRule:d.pricingRule,sizes:d.sizes,flavors:d.flavors,doughs:d.doughs,crusts:d.crusts,modifiers:d.modifiers,pizzas:d.pizzas}}
  setModule(tenantId:string,enabled:boolean){this.tenant(tenantId).enabled=enabled;this.save();return{enabled}}
  setPricingRule(tenantId:string,pricingRule:Rule){this.tenant(tenantId).pricingRule=pricingRule;this.save();return{pricingRule}}
  addSize(tenantId:string,input:{name:string;maxFlavors:number;serves?:number}){const d=this.tenant(tenantId);const value:Option={id:randomUUID(),name:input.name.trim(),active:true,maxFlavors:input.maxFlavors,serves:input.serves};d.sizes.push(value);this.save();return value}
  addNamed(tenantId:string,key:"flavors"|"doughs"|"crusts",name:string){const value:Option={id:randomUUID(),name:name.trim(),active:true};this.tenant(tenantId)[key].push(value);this.save();return value}
  addModifier(tenantId:string,input:{name:string;kind:"ADDITION"|"REMOVAL";price:number}){const value:Option={id:randomUUID(),name:input.name.trim(),kind:input.kind,price:input.price,active:true};this.tenant(tenantId).modifiers.push(value);this.save();return value}
  createPizza(tenantId:string,input:any){const d=this.tenant(tenantId),sizes=input.sizes.map((row:any)=>{const item=d.sizes.find(option=>option.id===row.sizeId);if(!item)throw new BadRequestException("Tamanho inválido.");return{...item,price:row.price}}),flavors=input.flavors.map((row:any)=>{const item=d.flavors.find(option=>option.id===row.flavorId);if(!item)throw new BadRequestException("Sabor inválido.");return{...item,price:row.price}}),modifiers=(input.modifierIds??[]).map((id:string)=>{const item=d.modifiers.find(option=>option.id===id);if(!item)throw new BadRequestException("Adicional inválido.");return item});const pizza:Pizza={id:randomUUID(),productId:randomUUID(),name:input.name.trim(),sku:input.sku.trim(),active:true,sizes,flavors,modifiers};d.pizzas.push(pizza);this.save();return pizza}
  quote(tenantId:string,input:any){const d=this.tenant(tenantId),pizza=d.pizzas.find(item=>item.id===input.pizzaProductId&&item.active);if(!pizza)throw new NotFoundException("Pizza não encontrada.");const size=pizza.sizes.find(item=>item.id===input.sizeId);if(!size)throw new BadRequestException("Tamanho indisponível.");const selected=input.flavors.map((row:any)=>pizza.flavors.find(item=>item.id===row.id));if(selected.some((item:any)=>!item)||selected.length>Number(size.maxFlavors??1))throw new BadRequestException("Sabores indisponíveis.");const fraction=input.flavors.reduce((sum:number,row:any)=>sum+row.fraction,0);if(Math.abs(fraction-1)>.001)throw new BadRequestException("As frações dos sabores devem somar 1.");const modifiers=(input.modifierIds??[]).map((id:string)=>pizza.modifiers.find(item=>item.id===id));if(modifiers.some((item:any)=>!item))throw new BadRequestException("Adicional indisponível.");const flavorAmount=calculateFlavorPrice(d.pricingRule,Number(size.price??0),selected.map((item:any,index:number)=>({price:Number(item.price??0),fraction:input.flavors[index].fraction}))),dough=input.doughId?d.doughs.find(item=>item.id===input.doughId):undefined,crust=input.crustId?d.crusts.find(item=>item.id===input.crustId):undefined,modifierAmount=modifiers.reduce((sum:number,item:any)=>sum+Number(item.price??0),0);if(input.doughId&&!dough||input.crustId&&!crust)throw new BadRequestException("Massa ou borda indisponível.");const total=Number((flavorAmount+modifierAmount).toFixed(2));return{pizzaProductId:pizza.id,productId:pizza.productId,sizeId:size.id,pricingRule:d.pricingRule,flavorAmount:Number(flavorAmount.toFixed(2)),doughAmount:0,crustAmount:0,modifierAmount,total}}
  operations(tenantId:string){const d=this.tenant(tenantId),today=new Date().toDateString(),orders=d.orders.filter(order=>!["COMPLETED","CANCELLED"].includes(order.status)),todayOrders=d.orders.filter(order=>new Date(order.createdAt).toDateString()===today&&order.status!=="CANCELLED"),paidRevenue=todayOrders.filter(order=>order.paymentState==="PAID").reduce((sum,order)=>sum+order.total,0),count=(states:string[])=>orders.filter(order=>states.includes(order.status)).length;return{orders,summary:{todayOrders:todayOrders.length,paidRevenue,new:count(["NEW"]),preparing:count(["PREPARING","OVEN"]),ready:count(["READY","OUT_FOR_DELIVERY"])}}}
  createOrder(tenantId:string,input:any){const d=this.tenant(tenantId),quoted=input.items.map((item:any)=>this.quote(tenantId,item)),order:Order={id:randomUUID(),number:d.orders.length+1,status:"NEW",serviceType:input.serviceType,paymentState:"PENDING",customerId:input.customerId||undefined,customerName:input.customerName?.trim()||undefined,customerPhone:input.customerPhone?.trim()||undefined,address:input.address?.trim()||undefined,notes:input.notes?.trim()||undefined,total:0,createdAt:new Date().toISOString(),items:[]};order.items=input.items.map((item:any,index:number)=>{const pizza=d.pizzas.find(value=>value.id===quoted[index].pizzaProductId)!;const total=quoted[index].total*item.quantity;return{id:randomUUID(),pizzaProductId:pizza.id,name:pizza.name,quantity:item.quantity,unitPrice:quoted[index].total,total,selection:{sizeId:item.sizeId,flavors:item.flavors,doughId:item.doughId??null,crustId:item.crustId??null,modifierIds:item.modifierIds??[],pricingRule:quoted[index].pricingRule}}});order.total=Number(order.items.reduce((sum,item)=>sum+item.total,0).toFixed(2));d.orders.push(order);this.save();return order}
  setStatus(tenantId:string,id:string,status:string){const order=this.tenant(tenantId).orders.find(item=>item.id===id);if(!order)throw new NotFoundException("Pedido não encontrado.");if(["COMPLETED","CANCELLED"].includes(order.status))throw new BadRequestException("Pedido concluído não pode ser alterado.");order.status=status;this.save();return order}
  setPayment(tenantId:string,id:string,paid:boolean){const order=this.tenant(tenantId).orders.find(item=>item.id===id);if(!order)throw new NotFoundException("Pedido não encontrado.");order.paymentState=paid?"PAID":"PENDING";this.save();return order}
}
