"use client";
import { FormEvent, useEffect, useState } from "react";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:3101/api";
type Session={accessToken:string;tenant:{tenantId:string;name:string;state?:string};user:{name:string;roles:string[]}};
type Product={id:string;sku:string;name:string;price:number;quantity:number};
type Setup={settings:any;products:Product[];cash:boolean;sales:number};

export default function Onboarding(){
 const[session,setSession]=useState<Session|null>(null),[data,setData]=useState<Setup>({settings:null,products:[],cash:false,sales:0}),[msg,setMsg]=useState(""),[error,setError]=useState("");
 async function call(path:string,t=session?.accessToken,init?:RequestInit){if(!t)throw Error("Sessão expirada");const r=await fetch(API+path,{...init,headers:{authorization:`Bearer ${t}`,"content-type":"application/json"}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(Array.isArray(j.message)?j.message.join(", "):j.message??"Operação não concluída");return j}
 async function load(t=session?.accessToken){if(!t)return;try{const[settings,products,cash,sales]=await Promise.all([call("/commercial/fiscal/settings",t),call("/products",t),call("/cash/current",t),call("/sales/summary",t)]);setData({settings,products,cash:!!cash.session,sales:sales.orders});setError("")}catch(e){setError((e as Error).message)}}
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("varejo-session")??"null");if(!saved?.accessToken){location.replace("/");return}if(saved.user?.roles?.includes("PLATFORM_ADMIN")){location.replace("/admin");return}setSession(saved);void load(saved.accessToken)}catch{location.replace("/")}},[]);
 async function configure(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await call("/commercial/fiscal/settings",undefined,{method:"PUT",body:JSON.stringify({state:f.get("state"),taxRegime:f.get("taxRegime"),stateRegistration:f.get("stateRegistration"),cityCode:f.get("cityCode"),nfeSeries:1,nfceSeries:1})});setMsg("Dados da empresa configurados.");await load()}catch(err){setError((err as Error).message)}}
 async function addProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();const target=e.currentTarget,f=new FormData(target);try{const product=await call("/products",undefined,{method:"POST",body:JSON.stringify({sku:f.get("sku"),name:f.get("name"),price:Number(f.get("price"))})});const quantity=Number(f.get("quantity"));if(quantity>0)await call("/inventory/adjustments",undefined,{method:"POST",body:JSON.stringify({productId:product.id,quantity,note:"Estoque inicial do onboarding"})});target.reset();setMsg("Primeiro produto e estoque cadastrados.");await load()}catch(err){setError((err as Error).message)}}
 async function openCash(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await call("/cash/open",undefined,{method:"POST",body:JSON.stringify({openingAmount:Number(f.get("amount"))})});setMsg("Caixa aberto com sucesso.");await load()}catch(err){setError((err as Error).message)}}
 async function firstSale(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await call("/sales/checkout",undefined,{method:"POST",body:JSON.stringify({items:[{productId:f.get("productId"),quantity:Number(f.get("quantity"))}],paymentMethod:f.get("paymentMethod")})});setMsg("Primeira venda concluída. Sua operação está pronta!");await load()}catch(err){setError((err as Error).message)}}
 function finish(){if(session)localStorage.setItem(`varejo-onboarding-seen:${session.tenant.tenantId}`,"true");location.href="/"}
 const configured=!!data.settings?.stateRegistration&&!!data.settings?.cityCode,steps=[configured,data.products.length>0,data.cash,data.sales>0],done=steps.filter(Boolean).length;
 if(!session)return <div className="management"><p>Preparando seus primeiros passos...</p></div>;
 return <div className="management onboarding"><header><div><small>CONFIGURAÇÃO GUIADA</small><h1>Vamos preparar {session.tenant.name}</h1></div><button className="secondary" onClick={finish}>Pular por agora</button></header><div className="progress"><i style={{width:`${done*25}%`}}/></div><p>{done} de 4 etapas concluídas</p>{error&&<div className="error">{error}</div>}{msg&&<div className="success">{msg}</div>}<div className="onboarding-steps"><Step n={1} done={configured} title="Configure a empresa" text="Informe os dados fiscais básicos da unidade.">{!configured&&<form onSubmit={configure}><select name="state" defaultValue={session.tenant.state??"SP"}><option>SP</option><option>RJ</option></select><select name="taxRegime" defaultValue="SIMPLES_NACIONAL"><option value="SIMPLES_NACIONAL">Simples Nacional</option><option value="REGIME_NORMAL">Regime normal</option></select><input name="stateRegistration" placeholder="Inscrição estadual" required/><input name="cityCode" placeholder="Código IBGE (7 dígitos)" minLength={7} maxLength={7} required/><button>Salvar empresa</button></form>}</Step><Step n={2} done={data.products.length>0} title="Cadastre o primeiro produto" text="Inclua preço e saldo inicial para poder vender.">{data.products.length===0&&<form onSubmit={addProduct}><input name="sku" placeholder="SKU" required/><input name="name" placeholder="Nome do produto" required/><input name="price" type="number" min="0.01" step="0.01" placeholder="Preço" required/><input name="quantity" type="number" min="0.001" step="0.001" placeholder="Quantidade" required/><button>Cadastrar produto</button></form>}</Step><Step n={3} done={data.cash} title="Abra o caixa" text="Defina o fundo de troco inicial.">{!data.cash&&<form onSubmit={openCash}><input name="amount" type="number" min="0" step="0.01" defaultValue="100" required/><button>Abrir caixa</button></form>}</Step><Step n={4} done={data.sales>0} title="Faça a primeira venda" text="Finalize uma venda guiada para validar a operação.">{data.sales===0&&<form onSubmit={firstSale}><select name="productId" required><option value="">Escolha um produto</option>{data.products.filter(p=>p.quantity>0).map(p=><option key={p.id} value={p.id}>{p.name} — saldo {p.quantity}</option>)}</select><input name="quantity" type="number" min="1" step="1" defaultValue="1" required/><select name="paymentMethod"><option value="PIX">PIX</option><option value="DINHEIRO">Dinheiro</option><option value="CREDITO">Crédito</option><option value="DEBITO">Débito</option></select><button disabled={!data.cash||!data.products.some(p=>p.quantity>0)}>Concluir primeira venda</button></form>}</Step></div>{done===4&&<div className="onboarding-finish"><h2>Configuração concluída!</h2><p>Empresa, produto, caixa e venda foram validados.</p><button onClick={finish}>Entrar no painel</button></div>}</div>
}

function Step({n,done,title,text,children}:{n:number;done:boolean;title:string;text:string;children?:React.ReactNode}){return <article className={done?"done":""}><b>{n}</b><div><h3>{title}</h3><p>{text}</p>{children}</div><span>{done?"✓":""}</span></article>}
