import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { randomUUID, scryptSync, timingSafeEqual } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
export type DemoUser={id:string;tenantId:string;name:string;email:string;passwordHash:string;roles:string[]};
export type DemoProduct={id:string;tenantId:string;sku:string;name:string;price:number;ncm?:string;cest?:string;cfop?:string;csosn?:string;pisCst?:string;cofinsCst?:string;active:boolean;createdAt:string};
export type DemoMovement={id:string;tenantId:string;productId:string;type:"ENTRY"|"SALE"|"ADJUSTMENT"|"REVERSAL";quantity:number;note:string;createdAt:string};
export type DemoOrder={id:string;tenantId:string;cashSessionId?:string;number:number;items:Array<{productId:string;name:string;quantity:number;unitPrice:number;total:number}>;paymentMethod:string;total:number;status:"PAID"|"CANCELLED";createdAt:string;cancelledAt?:string;cancelReason?:string};
export type DemoCashSession={id:string;tenantId:string;status:"OPEN"|"CLOSED";openingAmount:number;openedAt:string;closedAt?:string;declaredAmount?:number;difference?:number};
export type DemoCashMovement={id:string;tenantId:string;cashSessionId:string;type:"OPENING"|"SALE"|"SUPPLY"|"WITHDRAWAL"|"REVERSAL";amount:number;paymentMethod:string;note:string;orderId?:string;createdAt:string};
type DemoData={tenant:{id:string;name:string;document:string};branch:{id:string;name:string;state:string};users:DemoUser[];products:DemoProduct[];movements:DemoMovement[];orders:DemoOrder[];cashSessions:DemoCashSession[];cashMovements:DemoCashMovement[]};
export const hashPassword=(password:string,salt=randomUUID())=>`${salt}:${scryptSync(password,salt,64).toString("hex")}`;
export const passwordMatches=(password:string,stored:string)=>{try{const[salt,hash]=stored.split(":");if(!salt||!hash)return false;const expected=Buffer.from(hash,"hex"),actual=scryptSync(password,salt,64);return expected.length===actual.length&&timingSafeEqual(expected,actual)}catch{return false}};
@Injectable()
export class DemoStore{
  private readonly file=resolve(process.cwd(),"../../storage/demo-data.json");private data:DemoData;
  constructor(){this.data=this.load()}
  private seed():DemoData{const tenantId="10000000-0000-4000-8000-000000000001";const products:DemoProduct[]=[{id:randomUUID(),tenantId,sku:"REF-001",name:"Refrigerante lata",price:7.5,ncm:"22021000",active:true,createdAt:new Date().toISOString()},{id:randomUUID(),tenantId,sku:"POR-001",name:"Porção da casa",price:39.9,active:true,createdAt:new Date().toISOString()}];return{tenant:{id:tenantId,name:"Loja Demonstração",document:"12.345.678/0001-90"},branch:{id:"20000000-0000-4000-8000-000000000001",name:"Unidade Centro",state:"SP"},users:[{id:"30000000-0000-4000-8000-000000000001",tenantId,name:"Administrador",email:"admin@demo.com",passwordHash:hashPassword("Demo@123"),roles:["ADMIN"]}],products,movements:products.map(product=>({id:randomUUID(),tenantId,productId:product.id,type:"ENTRY",quantity:20,note:"Saldo inicial",createdAt:new Date().toISOString()})),orders:[],cashSessions:[],cashMovements:[]}}
  private load():DemoData{try{const data=JSON.parse(readFileSync(this.file,"utf8")) as Partial<DemoData>;return{...data,movements:data.movements??(data.products??[]).map(product=>({id:randomUUID(),tenantId:product.tenantId,productId:product.id,type:"ENTRY" as const,quantity:20,note:"Saldo inicial",createdAt:new Date().toISOString()})),orders:(data.orders??[]).map(order=>({...order,status:order.status??"PAID"})),cashSessions:data.cashSessions??[],cashMovements:data.cashMovements??[]} as DemoData}catch{const data=this.seed();this.save(data);return data}}
  private save(data=this.data){mkdirSync(dirname(this.file),{recursive:true});writeFileSync(this.file,JSON.stringify(data,null,2))}
  findUser(email:string){return this.data.users.find(user=>user.email.toLowerCase()===email.toLowerCase())}
  tenant(){return{...this.data.tenant,branch:this.data.branch}}
  users(tenantId:string){return this.data.users.filter(user=>user.tenantId===tenantId).map(({passwordHash:_,...user})=>user)}
  addUser(tenantId:string,input:{name:string;email:string;password:string;role:string}){if(this.data.users.some(user=>user.email.toLowerCase()===input.email.toLowerCase()))throw new BadRequestException("Este e-mail já está cadastrado");if(this.data.users.filter(user=>user.tenantId===tenantId).length>=2)throw new BadRequestException("Limite de 2 usuários atingido para este plano");const user={id:randomUUID(),tenantId,name:input.name.trim(),email:input.email.toLowerCase(),passwordHash:hashPassword(input.password),roles:[input.role]};this.data.users.push(user);this.save();const{passwordHash:_,...safe}=user;return safe}
  changePassword(tenantId:string,userId:string,currentPassword:string,newPassword:string){const user=this.data.users.find(item=>item.id===userId&&item.tenantId===tenantId);if(!user||!passwordMatches(currentPassword,user.passwordHash))throw new BadRequestException("Senha atual incorreta");user.passwordHash=hashPassword(newPassword);this.save();return{message:"Senha alterada com sucesso"}}
  products(tenantId:string){return this.data.products.filter(product=>product.tenantId===tenantId)}
  addProduct(tenantId:string,input:{sku:string;name:string;price:number;ncm?:string}){if(this.data.products.some(item=>item.tenantId===tenantId&&item.sku===input.sku))throw new BadRequestException("SKU já cadastrado");const product={id:randomUUID(),tenantId,...input,active:true,createdAt:new Date().toISOString()};this.data.products.push(product);this.save();return product}
  updateProductFiscal(tenantId:string,id:string,input:{ncm:string;cest?:string;cfop:string;csosn:string;pisCst:string;cofinsCst:string}){const product=this.data.products.find(p=>p.id===id&&p.tenantId===tenantId);if(!product)throw new NotFoundException("Produto não encontrado");Object.assign(product,input);this.save();return product}
  stock(tenantId:string){return this.products(tenantId).map(product=>({...product,quantity:this.balance(tenantId,product.id)}))}
  movements(tenantId:string){return this.data.movements.filter(item=>item.tenantId===tenantId).slice().reverse().map(item=>({...item,product:this.data.products.find(product=>product.id===item.productId)?.name??"Produto removido"}))}
  adjustStock(tenantId:string,productId:string,quantity:number,note:string){if(!this.data.products.some(product=>product.id===productId&&product.tenantId===tenantId))throw new NotFoundException("Produto não encontrado");if(quantity===0)throw new BadRequestException("A quantidade não pode ser zero");if(this.balance(tenantId,productId)+quantity<0)throw new BadRequestException("O ajuste deixaria o estoque negativo");const movement:DemoMovement={id:randomUUID(),tenantId,productId,type:quantity>0?"ENTRY":"ADJUSTMENT",quantity,note,createdAt:new Date().toISOString()};this.data.movements.push(movement);this.save();return movement}
  orders(tenantId:string){return this.data.orders.filter(order=>order.tenantId===tenantId).slice().reverse()}
  checkout(tenantId:string,input:{items:Array<{productId:string;quantity:number}>;paymentMethod:string}){const cash=this.openCash(tenantId);if(!cash)throw new BadRequestException("Abra o caixa antes de realizar uma venda");if(!input.items.length)throw new BadRequestException("Adicione ao menos um produto");const consolidated=new Map<string,number>();for(const item of input.items)consolidated.set(item.productId,(consolidated.get(item.productId)??0)+item.quantity);const items=[...consolidated].map(([productId,quantity])=>{const product=this.data.products.find(p=>p.id===productId&&p.tenantId===tenantId);if(!product)throw new NotFoundException("Produto não encontrado");if(quantity<=0||this.balance(tenantId,productId)<quantity)throw new BadRequestException(`Estoque insuficiente para ${product.name}`);return{productId,name:product.name,quantity,unitPrice:product.price,total:Number((product.price*quantity).toFixed(2))}});const now=new Date().toISOString();const order:DemoOrder={id:randomUUID(),tenantId,cashSessionId:cash.id,number:this.data.orders.filter(o=>o.tenantId===tenantId).length+1,items,paymentMethod:input.paymentMethod,total:Number(items.reduce((sum,item)=>sum+item.total,0).toFixed(2)),status:"PAID",createdAt:now};this.data.orders.push(order);this.data.cashMovements.push({id:randomUUID(),tenantId,cashSessionId:cash.id,type:"SALE",amount:order.total,paymentMethod:order.paymentMethod,note:`Venda #${order.number}`,orderId:order.id,createdAt:now});for(const item of items)this.data.movements.push({id:randomUUID(),tenantId,productId:item.productId,type:"SALE",quantity:-item.quantity,note:`Venda #${order.number}`,createdAt:now});this.save();return order}
  cancelOrder(tenantId:string,orderId:string,reason:string){const cash=this.openCash(tenantId);if(!cash)throw new BadRequestException("Abra o caixa para cancelar a venda");const order=this.data.orders.find(item=>item.id===orderId&&item.tenantId===tenantId);if(!order)throw new NotFoundException("Venda não encontrada");if(order.status==="CANCELLED")throw new BadRequestException("Venda já cancelada");const now=new Date().toISOString();order.status="CANCELLED";order.cancelledAt=now;order.cancelReason=reason;for(const item of order.items)this.data.movements.push({id:randomUUID(),tenantId,productId:item.productId,type:"REVERSAL",quantity:item.quantity,note:`Estorno venda #${order.number}`,createdAt:now});this.data.cashMovements.push({id:randomUUID(),tenantId,cashSessionId:cash.id,type:"REVERSAL",amount:-order.total,paymentMethod:order.paymentMethod,note:`Cancelamento venda #${order.number}: ${reason}`,orderId:order.id,createdAt:now});this.save();return order}
  currentCash(tenantId:string){const session=this.openCash(tenantId);if(!session)return{session:null,summary:null,movements:[]};return{session,summary:this.cashSummary(session.id),movements:this.data.cashMovements.filter(item=>item.cashSessionId===session.id).slice().reverse()}}
  openCashRegister(tenantId:string,openingAmount:number){if(this.openCash(tenantId))throw new BadRequestException("Já existe um caixa aberto");if(openingAmount<0)throw new BadRequestException("O valor inicial não pode ser negativo");const now=new Date().toISOString();const session:DemoCashSession={id:randomUUID(),tenantId,status:"OPEN",openingAmount,openedAt:now};this.data.cashSessions.push(session);this.data.cashMovements.push({id:randomUUID(),tenantId,cashSessionId:session.id,type:"OPENING",amount:openingAmount,paymentMethod:"DINHEIRO",note:"Abertura do caixa",createdAt:now});this.save();return this.currentCash(tenantId)}
  cashMovement(tenantId:string,type:"SUPPLY"|"WITHDRAWAL",amount:number,note:string){const cash=this.openCash(tenantId);if(!cash)throw new BadRequestException("Não existe caixa aberto");if(amount<=0)throw new BadRequestException("Informe um valor maior que zero");const signed=type==="WITHDRAWAL"?-amount:amount;if(this.cashSummary(cash.id).expectedCash+signed<0)throw new BadRequestException("Saldo em dinheiro insuficiente");this.data.cashMovements.push({id:randomUUID(),tenantId,cashSessionId:cash.id,type,amount:signed,paymentMethod:"DINHEIRO",note,createdAt:new Date().toISOString()});this.save();return this.currentCash(tenantId)}
  closeCashRegister(tenantId:string,declaredAmount:number){const cash=this.openCash(tenantId);if(!cash)throw new BadRequestException("Não existe caixa aberto");const summary=this.cashSummary(cash.id);cash.status="CLOSED";cash.closedAt=new Date().toISOString();cash.declaredAmount=declaredAmount;cash.difference=Number((declaredAmount-summary.expectedCash).toFixed(2));this.save();return{session:cash,summary}}
  summary(tenantId:string){const orders=this.orders(tenantId).filter(order=>order.status==="PAID");return{products:this.products(tenantId).length,stockUnits:this.stock(tenantId).reduce((sum,item)=>sum+item.quantity,0),orders:orders.length,revenue:Number(orders.reduce((sum,item)=>sum+item.total,0).toFixed(2)),cashOpen:Boolean(this.openCash(tenantId))}}
  private openCash(tenantId:string){return this.data.cashSessions.find(item=>item.tenantId===tenantId&&item.status==="OPEN")}
  private cashSummary(sessionId:string){const movements=this.data.cashMovements.filter(item=>item.cashSessionId===sessionId);const byPayment:Record<string,number>={};for(const item of movements)if(item.type==="SALE"||item.type==="REVERSAL")byPayment[item.paymentMethod]=Number(((byPayment[item.paymentMethod]??0)+item.amount).toFixed(2));const expectedCash=Number(movements.filter(item=>item.paymentMethod==="DINHEIRO").reduce((sum,item)=>sum+item.amount,0).toFixed(2));return{expectedCash,byPayment,sales:Number(movements.filter(item=>item.type==="SALE").reduce((sum,item)=>sum+item.amount,0).toFixed(2)),supplies:Number(movements.filter(item=>item.type==="SUPPLY").reduce((sum,item)=>sum+item.amount,0).toFixed(2)),withdrawals:Number(Math.abs(movements.filter(item=>item.type==="WITHDRAWAL").reduce((sum,item)=>sum+item.amount,0)).toFixed(2))}}
  private balance(tenantId:string,productId:string){return this.data.movements.filter(item=>item.tenantId===tenantId&&item.productId===productId).reduce((sum,item)=>sum+item.quantity,0)}
}
