import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { withTenant } from "@varejo/database";
import { DemoStore } from "./demo-store.service";

const number = (value: unknown) => Number(value ?? 0);

@Injectable()
export class OperationalStore {
  constructor(private readonly demo: DemoStore) {}
  private get useDemo() { return process.env.DEMO_MODE !== "false"; }

  async products(tenantId:string){
    if(this.useDemo)return this.demo.products(tenantId);
    const rows=await withTenant(tenantId,tx=>tx.product.findMany({where:{tenantId},orderBy:{createdAt:"desc"}}));
    return rows.map(p=>({...p,price:number(p.price),cost:number(p.cost)}));
  }
  async stock(tenantId:string,branchId?:string){if(this.useDemo)return this.demo.stock(tenantId);return withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId),products=await tx.product.findMany({where:{tenantId},orderBy:{createdAt:"desc"}}),totals=await tx.stockMovement.groupBy({by:["productId"],where:{tenantId,warehouse:{branchId:branch.id}},_sum:{quantity:true}}),map=new Map(totals.map(x=>[x.productId,number(x._sum.quantity)]));return products.map(p=>({...p,price:number(p.price),cost:number(p.cost),quantity:map.get(p.id)??0}))})}
  async addProduct(tenantId:string,input:{sku:string;name:string;price:number;ncm?:string}){if(this.useDemo)return this.demo.addProduct(tenantId,input);try{return await withTenant(tenantId,tx=>tx.product.create({data:{tenantId,sku:input.sku.trim(),name:input.name.trim(),price:input.price,ncm:input.ncm}})).then(p=>({...p,price:number(p.price),cost:number(p.cost),quantity:0}))}catch(e:any){if(e?.code==="P2002")throw new BadRequestException("SKU já cadastrado");throw e}}
  async importProducts(tenantId:string,items:Array<{sku:string;name:string;price:number;quantity:number;ncm?:string}>,branchId?:string){
    if(new Set(items.map(i=>i.sku.trim().toLowerCase())).size!==items.length)throw new BadRequestException("A lista contém SKUs repetidos");
    if(this.useDemo){for(const item of items){const product=await this.demo.addProduct(tenantId,item);if(item.quantity>0)await this.demo.adjustStock(tenantId,product.id,item.quantity,"Estoque inicial importado")}return{created:items.length}}
    try{return await withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId),warehouse=await tx.warehouse.findFirst({where:{tenantId,branchId:branch.id}});if(!warehouse)throw new BadRequestException("Estoque principal não configurado");for(const item of items){const product=await tx.product.create({data:{tenantId,sku:item.sku.trim(),name:item.name.trim(),price:item.price,ncm:item.ncm}});if(item.quantity>0)await tx.stockMovement.create({data:{tenantId,warehouseId:warehouse.id,productId:product.id,type:"ADJUSTMENT",quantity:item.quantity,unitCost:0}})}return{created:items.length}})}catch(e:any){if(e?.code==="P2002")throw new BadRequestException("Um dos SKUs já está cadastrado");throw e}
  }
  async updateProductFiscal(tenantId:string,id:string,input:{ncm:string;cest?:string;cfop:string;csosn:string;pisCst:string;cofinsCst:string}){if(this.useDemo)return this.demo.updateProductFiscal(tenantId,id,input);try{return await withTenant(tenantId,tx=>tx.product.update({where:{id,tenantId},data:input}))}catch(e:any){if(e?.code==="P2025")throw new NotFoundException("Produto não encontrado");throw e}}
  async movements(tenantId:string,branchId?:string){if(this.useDemo)return this.demo.movements(tenantId);const rows=await withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId);return tx.stockMovement.findMany({where:{tenantId,warehouse:{branchId:branch.id}},include:{product:{select:{name:true}}},orderBy:{occurredAt:"desc"},take:100})});return rows.map(m=>({id:m.id,tenantId:m.tenantId,productId:m.productId,type:m.type,quantity:number(m.quantity),note:m.referenceId?`Referência ${m.referenceId}`:"Movimento de estoque",createdAt:m.occurredAt.toISOString(),product:m.product.name}))}
  async adjustStock(tenantId:string,productId:string,quantity:number,note:string,branchId?:string){if(this.useDemo)return this.demo.adjustStock(tenantId,productId,quantity,note);return withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId),product=await tx.product.findFirst({where:{id:productId,tenantId}});if(!product)throw new NotFoundException("Produto não encontrado");const total=await tx.stockMovement.aggregate({where:{tenantId,productId,warehouse:{branchId:branch.id}},_sum:{quantity:true}});if(number(total._sum.quantity)+quantity<0)throw new BadRequestException("O ajuste deixaria o estoque negativo");const warehouse=await tx.warehouse.findFirst({where:{tenantId,branchId:branch.id}});if(!warehouse)throw new BadRequestException("Estoque principal não configurado");const movement=await tx.stockMovement.create({data:{tenantId,warehouseId:warehouse.id,productId,type:"ADJUSTMENT",quantity,unitCost:product.cost}});return{...movement,quantity:number(movement.quantity),note,createdAt:movement.occurredAt.toISOString()}})}

  async currentCash(tenantId:string,branchId?:string){if(this.useDemo)return this.demo.currentCash(tenantId);return withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId),session=await tx.cashSession.findFirst({where:{tenantId,branchId:branch.id,status:"OPEN"},orderBy:{openedAt:"desc"}});if(!session)return{session:null,summary:null,movements:[]};const movements=await tx.cashMovement.findMany({where:{tenantId,cashSessionId:session.id},orderBy:{createdAt:"desc"}});return{session:this.cashSession(session),summary:this.cashSummary(movements),movements:movements.map(m=>({...m,amount:number(m.amount),createdAt:m.createdAt.toISOString()}))}})}
  async openCashRegister(tenantId:string,openingAmount:number,branchId?:string){if(this.useDemo)return this.demo.openCashRegister(tenantId,openingAmount);await withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId);if(await tx.cashSession.findFirst({where:{tenantId,branchId:branch.id,status:"OPEN"}}))throw new BadRequestException("Já existe um caixa aberto nesta filial");const session=await tx.cashSession.create({data:{tenantId,branchId:branch.id,openingAmount}});await tx.cashMovement.create({data:{tenantId,cashSessionId:session.id,type:"OPENING",amount:openingAmount,paymentMethod:"DINHEIRO",note:"Abertura do caixa"}})});return this.currentCash(tenantId,branchId)}
  async cashMovement(tenantId:string,type:"SUPPLY"|"WITHDRAWAL",amount:number,note:string,branchId?:string){if(this.useDemo)return this.demo.cashMovement(tenantId,type,amount,note);await withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId),session=await tx.cashSession.findFirst({where:{tenantId,branchId:branch.id,status:"OPEN"}});if(!session)throw new BadRequestException("Não existe caixa aberto nesta filial");const movements=await tx.cashMovement.findMany({where:{tenantId,cashSessionId:session.id}}),signed=type==="WITHDRAWAL"?-amount:amount;if(this.cashSummary(movements).expectedCash+signed<0)throw new BadRequestException("Saldo em dinheiro insuficiente");await tx.cashMovement.create({data:{tenantId,cashSessionId:session.id,type,amount:signed,paymentMethod:"DINHEIRO",note}})});return this.currentCash(tenantId,branchId)}
  async closeCashRegister(tenantId:string,declaredAmount:number,branchId?:string){if(this.useDemo)return this.demo.closeCashRegister(tenantId,declaredAmount);return withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId),session=await tx.cashSession.findFirst({where:{tenantId,branchId:branch.id,status:"OPEN"}});if(!session)throw new BadRequestException("Não existe caixa aberto nesta filial");const movements=await tx.cashMovement.findMany({where:{tenantId,cashSessionId:session.id}}),summary=this.cashSummary(movements),closed=await tx.cashSession.update({where:{id:session.id},data:{status:"CLOSED",closedAt:new Date(),declaredAmount,difference:declaredAmount-summary.expectedCash}});return{session:this.cashSession(closed),summary}})}

  async orders(tenantId:string,branchId?:string){if(this.useDemo)return this.demo.orders(tenantId);const rows=await withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId);return tx.order.findMany({where:{tenantId,branchId:branch.id},include:{items:{include:{product:{select:{name:true}}}},payments:true},orderBy:{createdAt:"desc"},take:100})});return rows.map(o=>this.order(o))}
  async checkout(tenantId:string,input:{items:Array<{productId:string;quantity:number}>;paymentMethod:string},branchId?:string){if(this.useDemo)return this.demo.checkout(tenantId,input);return withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId),cash=await tx.cashSession.findFirst({where:{tenantId,branchId:branch.id,status:"OPEN"}});if(!cash)throw new BadRequestException("Abra o caixa desta filial antes de realizar uma venda");const quantities=new Map<string,number>();for(const item of input.items)quantities.set(item.productId,(quantities.get(item.productId)??0)+item.quantity);const items=[] as Array<{productId:string;name:string;quantity:number;unitPrice:number;total:number}>;for(const[productId,quantity]of quantities){const product=await tx.product.findFirst({where:{id:productId,tenantId,active:true}});if(!product)throw new NotFoundException("Produto não encontrado");const balance=await tx.stockMovement.aggregate({where:{tenantId,productId,warehouse:{branchId:branch.id}},_sum:{quantity:true}});if(quantity<=0||number(balance._sum.quantity)<quantity)throw new BadRequestException(`Estoque insuficiente para ${product.name}`);items.push({productId,name:product.name,quantity,unitPrice:number(product.price),total:number(product.price)*quantity})}const last=await tx.order.findFirst({where:{tenantId,branchId:branch.id},orderBy:{number:"desc"},select:{number:true}}),orderNumber=(last?.number??0n)+1n,total=items.reduce((sum,item)=>sum+item.total,0);const order=await tx.order.create({data:{tenantId,branchId:branch.id,cashSessionId:cash.id,number:orderNumber,status:"PAID",channel:"PDV",subtotal:total,total,items:{create:items.map(i=>({tenantId,productId:i.productId,quantity:i.quantity,unitPrice:i.unitPrice,total:i.total}))},payments:{create:{tenantId,method:input.paymentMethod,amount:total,status:"PAID"}}},include:{items:{include:{product:{select:{name:true}}}},payments:true}});const warehouse=await tx.warehouse.findFirstOrThrow({where:{tenantId,branchId:branch.id}});for(const item of items)await tx.stockMovement.create({data:{tenantId,warehouseId:warehouse.id,productId:item.productId,type:"SALE",quantity:-item.quantity,unitCost:0,referenceId:order.id}});await tx.cashMovement.create({data:{tenantId,cashSessionId:cash.id,type:"SALE",amount:total,paymentMethod:input.paymentMethod,note:`Venda #${orderNumber}`,orderId:order.id}});return this.order(order)})}
  async cancelOrder(tenantId:string,orderId:string,reason:string,branchId?:string){if(this.useDemo)return this.demo.cancelOrder(tenantId,orderId,reason);return withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId),cash=await tx.cashSession.findFirst({where:{tenantId,branchId:branch.id,status:"OPEN"}});if(!cash)throw new BadRequestException("Abra o caixa desta filial para cancelar a venda");const order=await tx.order.findFirst({where:{id:orderId,tenantId,branchId:branch.id},include:{items:{include:{product:{select:{name:true}}}},payments:true}});if(!order)throw new NotFoundException("Venda não encontrada nesta filial");if(order.status==="CANCELLED")throw new BadRequestException("Venda já cancelada");const warehouse=await tx.warehouse.findFirstOrThrow({where:{tenantId,branchId:branch.id}});for(const item of order.items)await tx.stockMovement.create({data:{tenantId,warehouseId:warehouse.id,productId:item.productId,type:"REVERSAL",quantity:item.quantity,unitCost:0,referenceId:order.id}});await tx.cashMovement.create({data:{tenantId,cashSessionId:cash.id,type:"REVERSAL",amount:-number(order.total),paymentMethod:order.payments[0]?.method??"DINHEIRO",note:`Cancelamento venda #${order.number}: ${reason}`,orderId:order.id}});const updated=await tx.order.update({where:{id:order.id},data:{status:"CANCELLED",cancelledAt:new Date(),cancelReason:reason},include:{items:{include:{product:{select:{name:true}}}},payments:true}});return this.order(updated)})}
  async summary(tenantId:string,branchId?:string){if(this.useDemo)return this.demo.summary(tenantId);return withTenant(tenantId,async tx=>{const branch=await this.branch(tx,tenantId,branchId),[products,stock,orders,cash]=await Promise.all([tx.product.count({where:{tenantId}}),tx.stockMovement.aggregate({where:{tenantId,warehouse:{branchId:branch.id}},_sum:{quantity:true}}),tx.order.aggregate({where:{tenantId,branchId:branch.id,status:"PAID"},_count:true,_sum:{total:true}}),tx.cashSession.findFirst({where:{tenantId,branchId:branch.id,status:"OPEN"}})]);return{products,stockUnits:number(stock._sum.quantity),orders:orders._count,revenue:number(orders._sum.total),cashOpen:Boolean(cash)}})}

  private async branch(tx:any,tenantId:string,branchId?:string){const branch=branchId?await tx.branch.findFirst({where:{id:branchId,tenantId}}):await tx.branch.findFirst({where:{tenantId},orderBy:{createdAt:"asc"}});if(!branch)throw new BadRequestException("Filial inválida ou não configurada");return branch}
  private cashSession(s:any){return{...s,openingAmount:number(s.openingAmount),declaredAmount:s.declaredAmount==null?undefined:number(s.declaredAmount),difference:s.difference==null?undefined:number(s.difference),openedAt:s.openedAt.toISOString(),closedAt:s.closedAt?.toISOString()}}
  private cashSummary(movements:any[]){const byPayment:Record<string,number>={};for(const m of movements)if(m.type==="SALE"||m.type==="REVERSAL")byPayment[m.paymentMethod]=number(byPayment[m.paymentMethod])+number(m.amount);return{expectedCash:movements.filter(m=>m.paymentMethod==="DINHEIRO").reduce((s,m)=>s+number(m.amount),0),byPayment,sales:movements.filter(m=>m.type==="SALE").reduce((s,m)=>s+number(m.amount),0),supplies:movements.filter(m=>m.type==="SUPPLY").reduce((s,m)=>s+number(m.amount),0),withdrawals:Math.abs(movements.filter(m=>m.type==="WITHDRAWAL").reduce((s,m)=>s+number(m.amount),0))}}
  private order(o:any){return{id:o.id,tenantId:o.tenantId,cashSessionId:o.cashSessionId,number:Number(o.number),items:o.items.map((i:any)=>({productId:i.productId,name:i.product.name,quantity:number(i.quantity),unitPrice:number(i.unitPrice),total:number(i.total)})),paymentMethod:o.payments[0]?.method??"",total:number(o.total),status:o.status,createdAt:o.createdAt.toISOString(),cancelledAt:o.cancelledAt?.toISOString(),cancelReason:o.cancelReason}}
}
