"use client";
import{FormEvent,useEffect,useState}from"react";
import{OmegaCredit}from"../omega-credit";
import{BrandName}from"../brand-name";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:3101/api";
type Plan={code:"ESSENTIAL"|"PERFORMANCE"|"SCALE";name:string;amount:number;features:string[]};
type Info={name:string;status:string;subscriptionPlan?:string;subscriptionExpiresAt?:string;plans:Plan[];methods:string[]};
export default function Payment(){
  const[tenantId,setTenantId]=useState(""),[info,setInfo]=useState<Info|null>(null),[plan,setPlan]=useState<Plan["code"]>("PERFORMANCE"),[error,setError]=useState(""),[loading,setLoading]=useState(false),[result,setResult]=useState("");
  useEffect(()=>{const params=new URLSearchParams(location.search),id=params.get("cliente")??"",chosen=params.get("plano");setTenantId(id);setResult(params.get("resultado")??"");if(chosen==="ESSENTIAL"||chosen==="PERFORMANCE"||chosen==="SCALE")setPlan(chosen);if(id)fetch(`${API}/billing/public/${id}`).then(async r=>{const body=await r.json();if(!r.ok)throw Error(body.message??"Cobrança não encontrada");return body}).then(setInfo).catch(e=>setError(e.message));else setError("Link de pagamento inválido")},[]);
  async function checkout(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);try{const r=await fetch(`${API}/billing/public/${tenantId}/checkout`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:f.get("email"),plan})}),body=await r.json();if(!r.ok)throw Error(Array.isArray(body.message)?body.message.join(", "):body.message??"Pagamento indisponível");location.href=body.checkoutUrl}catch(e){setError((e as Error).message);setLoading(false)}}
  return <main className="payment-page"><section><div className="brand dark"><span>V</span> <BrandName /> <OmegaCredit /></div>{result&&<div className={result==="sucesso"?"success":"notice"}>{result==="sucesso"?"Pagamento recebido. Assim que o Mercado Pago confirmar, seus 30 dias serão liberados automaticamente.":result==="pendente"?"Pagamento pendente. Pix e boleto podem levar algum tempo para confirmação.":"O pagamento não foi concluído. Você pode tentar novamente."}</div>}<small>ASSINATURA VENDA+</small><h1>{info?.name??"Carregando cobrança..."}</h1>{info&&<><p>Escolha o plano. O pagamento libera 30 dias de acesso após a confirmação do Mercado Pago.</p><div className="payment-plans">{info.plans.map(item=><button type="button" className={plan===item.code?"selected":""} onClick={()=>setPlan(item.code)} key={item.code}><span>Plano {item.name}</span><strong>{item.amount.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}<small>/30 dias</small></strong><ul>{item.features.map(feature=><li key={feature}>{feature}</li>)}</ul></button>)}</div><p>Você concluirá no ambiente seguro do Mercado Pago.</p><div className="payment-methods">{info.methods.map(method=><span key={method}>{method}</span>)}</div><form onSubmit={checkout}><label>E-mail do pagador<input name="email" type="email" required/></label><button disabled={loading}>{loading?"Abrindo Mercado Pago...":"Pagar com Mercado Pago"}</button></form></>}{error&&<div className="error">{error}</div>}<a href="/">Voltar ao Venda+</a></section></main>;
}
