"use client";
import{FormEvent,useEffect,useState}from"react";
import{OmegaCredit}from"../omega-credit";
import{BrandName}from"../brand-name";
import{planComparison,type PlanCode}from"../plan-comparison";
import{billingCycles,cyclePrice,type BillingCycle}from"../pricing-periods";
const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:3101/api";
type Plan={code:PlanCode;name:string;amount:number;features:string[]};
type Info={name:string;status:string;subscriptionPlan?:string;subscriptionExpiresAt?:string;plans:Plan[];methods:string[]};
export default function Payment(){
  const[tenantId,setTenantId]=useState(""),[info,setInfo]=useState<Info|null>(null),[plan,setPlan]=useState<Plan["code"]>("PERFORMANCE"),[cycle,setCycle]=useState<BillingCycle>("MONTHLY"),[error,setError]=useState(""),[loading,setLoading]=useState(false),[result,setResult]=useState("");
  useEffect(()=>{const params=new URLSearchParams(location.search),id=params.get("cliente")??"",chosen=params.get("plano"),chosenCycle=params.get("ciclo");setTenantId(id);setResult(params.get("resultado")??"");if(chosen==="ESSENTIAL"||chosen==="PERFORMANCE"||chosen==="SCALE")setPlan(chosen);if(chosenCycle==="MONTHLY"||chosenCycle==="SEMIANNUAL"||chosenCycle==="ANNUAL")setCycle(chosenCycle);if(id)fetch(`${API}/billing/public/${id}`).then(async r=>{const body=await r.json();if(!r.ok)throw Error(body.message??"Cobrança não encontrada");return body}).then(setInfo).catch(e=>setError(e.message));else setError("Link de pagamento inválido")},[]);
  async function checkout(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);try{const r=await fetch(`${API}/billing/public/${tenantId}/checkout`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:f.get("email"),plan,cycle})}),body=await r.json();if(!r.ok)throw Error(Array.isArray(body.message)?body.message.join(", "):body.message??"Pagamento indisponível");location.href=body.checkoutUrl}catch(e){setError((e as Error).message);setLoading(false)}}
  const period=billingCycles.find(item=>item.code===cycle)!;
  return <main className="payment-page"><section><div className="brand dark"><span>V</span> <BrandName /> <OmegaCredit /></div>{result&&<div className={result==="sucesso"?"success":"notice"}>{result==="sucesso"?`Pagamento recebido. Assim que o Mercado Pago confirmar, seus ${period.days} dias serão liberados automaticamente.`:result==="pendente"?"Pagamento pendente. Pix e boleto podem levar algum tempo para confirmação.":"O pagamento não foi concluído. Você pode tentar novamente."}</div>}<small>ASSINATURA VENDA+</small><h1>{info?.name??"Carregando cobrança..."}</h1>{info&&<><p>Escolha o plano e o período. O acesso é liberado após a confirmação do Mercado Pago.</p><div className="billing-cycle-tabs">{billingCycles.map(item=><button type="button" className={cycle===item.code?"active":""} onClick={()=>setCycle(item.code)} key={item.code}>{item.label}{item.discount>0&&<small>Economize {item.discount*100}%</small>}</button>)}</div><div className="payment-plans">{info.plans.map(item=><button type="button" className={plan===item.code?"selected":""} onClick={()=>setPlan(item.code)} key={item.code}><span>Plano {item.name}</span><strong>{cyclePrice(item.amount,cycle).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}<small>/{period.label.toLowerCase()}</small></strong>{cycle!=="MONTHLY"&&<span className="payment-equivalent">equivale a R$ {(cyclePrice(item.amount,cycle)/period.months).toLocaleString("pt-BR",{minimumFractionDigits:2})} por mês</span>}<ul className="plan-feature-list">{planComparison.map(feature=>{const included=feature.included[item.code];return <li className={included?"included":"excluded"} key={feature.label}><i aria-hidden="true">{included?"✓":"×"}</i><span>{feature.label}</span><small className="sr-only">{included?"Incluído":"Não incluído"}</small></li>})}</ul></button>)}</div><p>Pix e boleto são pagos pelo total do período. No cartão, o Mercado Pago poderá oferecer até {period.months} parcela(s), sujeito à aprovação.</p><div className="payment-methods">{info.methods.map(method=><span key={method}>{method}</span>)}</div><form onSubmit={checkout}><label>E-mail do pagador<input name="email" type="email" required/></label><button disabled={loading}>{loading?"Abrindo Mercado Pago...":"Pagar com Mercado Pago"}</button></form></>}{error&&<div className="error">{error}</div>}<a href="/">Voltar ao Venda+</a></section></main>;
}
