"use client";

import { FormEvent, useEffect, useState } from "react";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:3101/api";
type Format="PDF"|"KINDLE";
type Category="NEGOCIOS"|"TECNOLOGIA"|"ESPIRITUALIDADE"|"SAUDE";
type Book={slug:string;category:Category;title:string;hook:string;pages:number;cover:string;available:Record<Format,boolean>};
type Member={email:string};
const categories:Array<{id:Category;title:string;description:string}>=[
  {id:"NEGOCIOS",title:"Negócios, vendas & finanças",description:"Persuasão, escolhas financeiras e decisões para avançar."},
  {id:"TECNOLOGIA",title:"Inteligência artificial & tecnologia",description:"Fundamentos e aplicações práticas para acompanhar o presente."},
  {id:"SAUDE",title:"Saúde & bem-estar",description:"Conteúdos sobre hábitos, alimentação e autocuidado."},
  {id:"ESPIRITUALIDADE",title:"Espiritualidade, simbolismo & autoconhecimento",description:"Tradições, símbolos e reflexões para novas perspectivas."}
];
const requestError=(body:unknown,fallback:string)=>body&&typeof body==="object"&&"message" in body?String((body as {message?:unknown}).message):fallback;

export default function BibliotecaMembros(){
  const[member,setMember]=useState<Member>(),[books,setBooks]=useState<Book[]>([]),[mode,setMode]=useState<"LOGIN"|"CHECKOUT">("CHECKOUT"),[loading,setLoading]=useState(false),[checking,setChecking]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const shelves=categories.map(category=>({...category,books:books.filter(book=>book.category===category.id)})).filter(category=>category.books.length);

  async function refreshMember(){
    const response=await fetch(`${API}/library-memberships/me`,{credentials:"include"});
    if(!response.ok){setMember(undefined);return false}
    const body=await response.json();setMember(body.member??body);return true;
  }
  async function refreshBooks(){
    const response=await fetch(`${API}/library-memberships/books`,{credentials:"include"});
    const body=await response.json();if(!response.ok)throw Error(requestError(body,"Não foi possível carregar seus livros."));setBooks(body);
  }

  useEffect(()=>{void refreshMember()},[]);
  useEffect(()=>{if(!member)return;void refreshBooks().catch(cause=>setError(cause instanceof Error?cause.message:"Não foi possível carregar seus livros."))},[member]);
  useEffect(()=>{
    const params=new URLSearchParams(location.search),purchaseId=params.get("compra"),token=params.get("token");if(!purchaseId||!token)return;
    let timer:number|undefined,cancelled=false;
    const check=async()=>{try{setChecking(true);const response=await fetch(`${API}/library-memberships/purchases/${purchaseId}?token=${encodeURIComponent(token)}`,{credentials:"include"}),body=await response.json();if(!response.ok)throw Error(requestError(body,"Não foi possível consultar o pagamento."));if(cancelled)return;if(body.status==="APPROVED"){setMessage("Pagamento aprovado. Sua área de membros está liberada.");history.replaceState({},"",location.pathname);await refreshMember();return}if(["REJECTED","CANCELLED","ERROR"].includes(body.status)){setError("O pagamento não foi aprovado. Você pode tentar novamente.");history.replaceState({},"",location.pathname);return}timer=window.setTimeout(check,3000)}catch(cause){if(!cancelled)setError(cause instanceof Error?cause.message:"Não foi possível consultar o pagamento.")}finally{if(!cancelled)setChecking(false)}};
    void check();return()=>{cancelled=true;if(timer)clearTimeout(timer)};
  },[]);

  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const data=new FormData(event.currentTarget);try{const response=await fetch(`${API}/library-memberships/login`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({email:data.get("email"),password:data.get("password")})}),body=await response.json();if(!response.ok)throw Error(requestError(body,"Não foi possível entrar."));setMember(body.member??body);setMessage("Acesso liberado. Boas leituras!")}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível entrar.")}finally{setLoading(false)}}
  async function checkout(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const data=new FormData(event.currentTarget),password=String(data.get("password")??"");if(password!==String(data.get("passwordConfirmation")??"")){setError("As senhas precisam ser iguais.");setLoading(false);return}try{const response=await fetch(`${API}/library-memberships/checkout`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({email:data.get("email"),password})}),body=await response.json();if(!response.ok)throw Error(requestError(body,"Não foi possível iniciar o pagamento."));location.href=body.checkoutUrl}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível iniciar o pagamento.");setLoading(false)}}
  async function logout(){await fetch(`${API}/library-memberships/logout`,{method:"POST",credentials:"include"});setMember(undefined);setBooks([]);setMessage("")}

  if(!member)return <main className="member-store"><header className="member-header"><a href="/biblioteca" className="member-brand"><i>V</i><b>Venda<span>+</span></b><small>Biblioteca digital</small></a><a href="/biblioteca">Ver biblioteca</a></header><section className="member-access"><div className="member-access-copy"><small>ÁREA DE MEMBROS</small><h1>Todos os livros, em um só lugar.</h1><p>Faça uma compra única de <b>R$ 59,90</b> e tenha uma área reservada para baixar as edições disponíveis em PDF e Kindle.</p><ul><li>Todos os livros disponíveis na biblioteca</li><li>PDF e Kindle · EPUB quando preparados</li><li>Login próprio, separado do sistema Venda+</li></ul><div className="member-access-note"><b>Espaço em evolução</b><span>Os conteúdos exclusivos da área de membros estão sendo preparados. Por enquanto, seu acesso completo à biblioteca já fica liberado.</span></div></div><section className="member-auth-card"><div className="member-auth-tabs"><button className={mode==="CHECKOUT"?"active":""} onClick={()=>{setMode("CHECKOUT");setError("")}}>Quero ser membro</button><button className={mode==="LOGIN"?"active":""} onClick={()=>{setMode("LOGIN");setError("")}}>Já tenho acesso</button></div>{checking&&<div className="member-payment-status">Confirmando seu pagamento…</div>}{error&&<div className="error member-error">{error}</div>}{mode==="CHECKOUT"?<form onSubmit={checkout}><small>ACESSO COMPLETO · R$ 59,90</small><h2>Crie seu acesso</h2><p>Você definirá sua senha agora e entrará automaticamente após a aprovação do pagamento.</p><label>E-mail<input type="email" name="email" required autoComplete="email" placeholder="voce@email.com"/></label><label>Crie uma senha<input type="password" name="password" required minLength={8} autoComplete="new-password" placeholder="Ao menos 8 caracteres"/></label><label>Confirme a senha<input type="password" name="passwordConfirmation" required minLength={8} autoComplete="new-password" placeholder="Repita sua senha"/></label><button disabled={loading}>{loading?"Abrindo Mercado Pago...":"Continuar para pagamento"}</button><small className="member-form-note">Pagamento processado com segurança pelo Mercado Pago.</small></form>:<form onSubmit={login}><small>ENTRAR NA ÁREA</small><h2>Que bom ver você de novo.</h2><p>Use o e-mail e a senha definidos na compra do acesso completo.</p><label>E-mail<input type="email" name="email" required autoComplete="email" placeholder="voce@email.com"/></label><label>Senha<input type="password" name="password" required autoComplete="current-password" placeholder="Sua senha"/></label><button disabled={loading}>{loading?"Entrando...":"Entrar na área de membros"}</button><button type="button" className="member-back" onClick={()=>setMode("CHECKOUT")}>Ainda não sou membro</button></form>}</section></section></main>;

  return <main className="member-store"><header className="member-header"><a href="/biblioteca" className="member-brand"><i>V</i><b>Venda<span>+</span></b><small>Biblioteca digital</small></a><div><a href="/biblioteca">Ver biblioteca</a><button onClick={()=>void logout()}>Sair</button></div></header>{message&&<div className="member-message">{message}</div>}{error&&<div className="error member-error">{error}</div>}<section className="member-hero"><div><small>ÁREA DE MEMBROS</small><h1>Sua biblioteca está liberada.</h1><p>Olá, {member.email}. Baixe as edições que quiser e volte sempre que precisar.</p></div><div><b>{books.length}</b><span>livros em sua biblioteca</span></div></section><section className="member-empty"><small>EM PREPARAÇÃO</small><h2>Este espaço vai ganhar mais conteúdos.</h2><p>Enquanto isso, todos os livros disponíveis já podem ser baixados abaixo.</p></section><div className="member-downloads">{shelves.map(shelf=><section className="member-shelf" key={shelf.id} aria-labelledby={`member-shelf-${shelf.id}`}><header><small>COLEÇÃO</small><h2 id={`member-shelf-${shelf.id}`}>{shelf.title}</h2><p>{shelf.description}</p></header><div>{shelf.books.map(book=><article key={book.slug}><img src={book.cover} alt={`Capa de ${book.title}`}/><section><h3>{book.title}</h3><span>Págs.: {book.pages}</span><p>{book.hook}</p><div className="member-download-actions">{book.available.PDF?<a href={`${API}/library-memberships/books/${book.slug}/PDF/download`}>Baixar PDF</a>:<em>PDF em preparação</em>}{book.available.KINDLE?<a className="kindle" href={`${API}/library-memberships/books/${book.slug}/KINDLE/download`}>Baixar Kindle</a>:<em className="kindle">Kindle em preparação</em>}</div></section></article>)}</div></section>)}</div></main>;
}
