import { ImageResponse } from "next/og";

export const alt = "Biblioteca digital Venda+ — livros em PDF e Kindle";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpenGraphImage() {
  const book = (title:string, tone:string, rotate:string) => <div style={{width:190,height:286,display:"flex",flexDirection:"column",justifyContent:"space-between",padding:"25px 22px",borderRadius:10,background:tone,color:"#fff",boxShadow:"0 22px 34px #00000055",transform:`rotate(${rotate})`,border:"1px solid #ffffff55"}}><div style={{display:"flex",fontSize:14,letterSpacing:2,color:"#f3c553"}}>BIBLIOTECA</div><div style={{display:"flex",fontSize:26,lineHeight:1.05,fontWeight:800}}>{title}</div><div style={{display:"flex",fontSize:14,letterSpacing:1}}>VENDA+</div></div>;
  return new ImageResponse(<div style={{height:"100%",width:"100%",display:"flex",overflow:"hidden",background:"#101b31",color:"white",fontFamily:"Arial, sans-serif"}}><div style={{position:"absolute",width:660,height:660,borderRadius:999,background:"#ddaa2f",opacity:.16,top:-330,right:-90}}/><div style={{position:"absolute",width:430,height:430,borderRadius:999,border:"2px solid #ffffff22",bottom:-270,left:420}}/><div style={{display:"flex",flexDirection:"column",width:"57%",padding:"66px 0 58px 74px",zIndex:1}}><div style={{display:"flex",alignItems:"center",gap:12,fontSize:22,fontWeight:800}}><span style={{display:"flex",width:40,height:40,alignItems:"center",justifyContent:"center",borderRadius:12,background:"#2da677"}}>V</span> Venda<span style={{color:"#edbd49"}}>+</span><span style={{fontSize:15,fontWeight:500,opacity:.7}}>Biblioteca digital</span></div><div style={{display:"flex",marginTop:50,fontSize:21,fontWeight:800,letterSpacing:3,color:"#edbd49"}}>CONHECIMENTO PARA GUARDAR</div><div style={{display:"flex",marginTop:18,fontSize:61,fontWeight:800,lineHeight:1.02,letterSpacing:-2}}>Livros que<br/>despertam novas<br/>perguntas.</div><div style={{display:"flex",marginTop:"auto",gap:15,fontSize:20}}><span style={{display:"flex",padding:"11px 17px",border:"1px solid #ffffff55",borderRadius:10}}>PDF · R$ 11,99</span><span style={{display:"flex",padding:"11px 17px",border:"1px solid #ffffff55",borderRadius:10}}>Kindle · R$ 39,99</span></div></div><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:20,width:"43%",paddingTop:75,zIndex:1}}>{book("CÓDIGOS\nDE ENERGIA","#326d80","-8deg")}{book("GEOMETRIA\nSAGRADA","#5e4e80","4deg")}{book("TÁBUAS DE\nESMERALDA","#935f2d","-3deg")}</div></div>, size);
}
