import { ImageResponse } from "next/og";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

export const alt = "Biblioteca digital Venda+ — livros em PDF e Kindle";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function OpenGraphImage() {
  const cover = async(name:string) => `data:image/png;base64,${(await readFile(join(process.cwd(), "public", "pdf-covers", name))).toString("base64")}`;
  const [codigos, geometria, tabuas] = await Promise.all([cover("codigos-de-energia-volume-1.png"), cover("geometria-sagrada-universal.png"), cover("tabuas-de-esmeralda-de-thoth.png")]);
  const book = (src:string, label:string, rotate:string) => <div style={{width:165,height:248,display:"flex",position:"relative",overflow:"hidden",borderRadius:10,background:"#fff",boxShadow:"0 22px 34px #00000055",transform:`rotate(${rotate})`,border:"1px solid #ffffff55"}}><img src={src} alt={label} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div>;
  return new ImageResponse(<div style={{height:"100%",width:"100%",display:"flex",overflow:"hidden",background:"#101b31",color:"white",fontFamily:"Arial, sans-serif"}}><div style={{position:"absolute",width:660,height:660,borderRadius:999,background:"#ddaa2f",opacity:.16,top:-330,right:-90}}/><div style={{position:"absolute",width:430,height:430,borderRadius:999,border:"2px solid #ffffff22",bottom:-270,left:420}}/><div style={{display:"flex",flexDirection:"column",width:"55%",padding:"66px 0 58px 74px",zIndex:1}}><div style={{display:"flex",alignItems:"center",gap:12,fontSize:22,fontWeight:800}}><span style={{display:"flex",width:40,height:40,alignItems:"center",justifyContent:"center",borderRadius:12,background:"#2da677"}}>V</span> Venda<span style={{color:"#edbd49"}}>+</span><span style={{fontSize:15,fontWeight:500,opacity:.7}}>Biblioteca digital</span></div><div style={{display:"flex",marginTop:50,fontSize:20,fontWeight:800,letterSpacing:3,color:"#edbd49"}}>CONHECIMENTO PARA GUARDAR</div><div style={{display:"flex",flexDirection:"column",marginTop:18,fontSize:52,fontWeight:800,lineHeight:1.02,letterSpacing:-2}}><div style={{display:"flex"}}>Livros que</div><div style={{display:"flex"}}>despertam novas</div><div style={{display:"flex"}}>perguntas.</div></div><div style={{display:"flex",marginTop:"auto",gap:15,fontSize:20}}><span style={{display:"flex",padding:"11px 17px",border:"1px solid #ffffff55",borderRadius:10}}>PDF · R$ 11,99</span><span style={{display:"flex",padding:"11px 17px",border:"1px solid #ffffff55",borderRadius:10}}>Kindle · R$ 39,99</span></div></div><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:14,width:"45%",paddingTop:75,zIndex:1}}>{book(codigos,"Códigos de Energia","-8deg")}{book(geometria,"Geometria Sagrada Universal","4deg")}{book(tabuas,"Tábuas de Esmeralda","-3deg")}</div></div>, size);
}
