"use client";
import { FormEvent, useEffect, useState } from "react";

const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:3101/api";
type Format="PDF"|"KINDLE";
type Book={slug:string;title:string;hook:string;cover:string;preview:string;prices:Record<Format,number>;available:Record<Format,boolean>};
type Selection={book:Book;format:Format};

export default function Biblioteca(){
  const[books,setBooks]=useState<Book[]>([]),[selection,setSelection]=useState<Selection>(),[preview,setPreview]=useState<Book>(),[error,setError]=useState(""),[loading,setLoading]=useState(false),[purchase,setPurchase]=useState<{status:string;title:string;format:Format;downloadUrl?:string}>();
  useEffect(()=>{fetch(`${API}/digital-products`).then(async response=>{const body=await response.json();if(!response.ok)throw Error(body.message);return body}).then(setBooks).catch(()=>setError("Não foi possível carregar a biblioteca."))},[]);
  useEffect(()=>{if(!books.length)return;const params=new URLSearchParams(location.search),slug=params.get("livro"),requested=params.get("formato")?.toUpperCase();if(!slug||!requested||!(["PDF","KINDLE"] as string[]).includes(requested))return;const book=books.find(item=>item.slug===slug);if(book)setSelection({book,format:requested as Format})},[books]);
  useEffect(()=>{const params=new URLSearchParams(location.search),id=params.get("compra"),token=params.get("token");if(!id||!token)return;let timer:number;const check=()=>fetch(`${API}/digital-products/purchases/${id}?token=${encodeURIComponent(token)}`).then(response=>response.json()).then(body=>{setPurchase(body);if(body.status!=="APPROVED")timer=window.setTimeout(check,3000)}).catch(()=>setError("Não foi possível consultar sua compra."));check();return()=>clearTimeout(timer)},[]);
  async function checkout(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selection)return;setLoading(true);setError("");const data=new FormData(event.currentTarget);try{const response=await fetch(`${API}/digital-products/${selection.book.slug}/checkout`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:data.get("email"),format:selection.format})}),body=await response.json();if(!response.ok)throw Error(Array.isArray(body.message)?body.message.join(", "):body.message);location.href=body.checkoutUrl}catch(cause){setError(cause instanceof Error?cause.message:"Pagamento indisponível");setLoading(false)}}
  return <main className="digital-store">
    <header className="digital-hero"><a href="/" className="digital-brand"><i>V</i><b>Venda<span>+</span></b><small>Biblioteca digital</small></a><div><small>CONHECIMENTO PARA GUARDAR</small><h1>Livros que despertam novas perguntas.</h1><p>Conheça páginas selecionadas, escolha o formato e receba o download após a aprovação do Mercado Pago.</p><div className="digital-prices"><b>PDF <span>R$ 11,99</span></b><b>Kindle · EPUB <span>R$ 39,99</span></b></div></div></header>
    {purchase&&<section className={purchase.status==="APPROVED"?"digital-purchase approved":"digital-purchase"}><div><small>SUA COMPRA</small><h2>{purchase.title}</h2><p>{purchase.status==="APPROVED"?`Pagamento aprovado. Sua versão ${purchase.format==="PDF"?"PDF":"Kindle"} está pronta.`:"Aguardando a confirmação do Mercado Pago. Esta tela atualiza automaticamente."}</p></div>{purchase.downloadUrl&&<a href={purchase.downloadUrl}>Baixar agora</a>}</section>}
    {error&&<div className="error digital-error">{error}</div>}
    <section className="digital-heading"><small>EXPLORE ANTES DE ESCOLHER</small><h2>Uma página certa pode abrir uma ideia inteira.</h2><p>Clique em “Ver páginas” para ampliar uma prévia. A demonstração é protegida e não substitui o livro completo.</p></section>
    <section className="digital-grid">{books.map(book=><article key={book.slug}><button className="digital-cover" onClick={()=>setPreview(book)}><img src={book.cover} alt={`Capa de ${book.title}`}/><span>Ver páginas</span></button><div><h3>{book.title}</h3><p>{book.hook}</p><button disabled={!book.available.PDF} onClick={()=>setSelection({book,format:"PDF"})}><span>PDF</span><b>{book.available.PDF?"R$ 11,99":"Em preparação"}</b></button><button disabled={!book.available.KINDLE} className="kindle" onClick={()=>setSelection({book,format:"KINDLE"})}><span>Kindle · EPUB</span><b>{book.available.KINDLE?"R$ 39,99":"Em preparação"}</b></button></div></article>)}</section>
    {preview&&<div className="digital-modal" role="dialog" aria-modal="true"><button className="digital-dismiss" onClick={()=>setPreview(undefined)}>×</button><div><img src={preview.cover} alt=""/><figure><img src={preview.preview} alt={`Página selecionada de ${preview.title}`}/><figcaption>PRÉVIA · Venda proibida e reprodução limitada</figcaption></figure></div><section><small>UMA LEITURA PARA DESPERTAR CURIOSIDADE</small><h2>{preview.title}</h2><p>{preview.hook}</p><button disabled={!preview.available.PDF} onClick={()=>{setSelection({book:preview,format:"PDF"});setPreview(undefined)}}>{preview.available.PDF?"Quero em PDF · R$ 11,99":"PDF em preparação"}</button><button disabled={!preview.available.KINDLE} className="kindle" onClick={()=>{setSelection({book:preview,format:"KINDLE"});setPreview(undefined)}}>{preview.available.KINDLE?"Quero para Kindle · R$ 39,99":"Kindle em preparação"}</button></section></div>}
    {selection&&<div className="checkout-modal" role="dialog" aria-modal="true"><button className="digital-dismiss" onClick={()=>setSelection(undefined)}>×</button><img src={selection.book.cover} alt=""/><section><small>COMPRA SEGURA</small><h2>{selection.book.title}</h2><div className="format-choice"><button className={selection.format==="PDF"?"active":""} onClick={()=>setSelection({...selection,format:"PDF"})}>PDF<b>R$ 11,99</b></button><button className={selection.format==="KINDLE"?"active":""} onClick={()=>setSelection({...selection,format:"KINDLE"})}>Kindle · EPUB<b>R$ 39,99</b></button></div><p>{selection.format==="PDF"?"Arquivo PDF para leitura em celular, computador ou tablet.":"EPUB de layout preservado, preparado para enviar ao aplicativo ou dispositivo Kindle."}</p><form onSubmit={checkout}><label>E-mail para identificar a compra<input type="email" name="email" required placeholder="voce@email.com"/></label><button disabled={loading}>{loading?"Abrindo Mercado Pago...":"Pagar com Mercado Pago"}</button></form><small>O download é liberado somente após a confirmação do pagamento.</small></section></div>}
  </main>;
}
